src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/resources/application.properties
src/main/resources/templates/home.html

home.html 생성&HomeController 생성했습니다.

:tada: [박혜선] home.html 생성

---

build.gradle
src/main/java/com/fiveLink/linkOffice/document/controller/DocumentController.java
src/main/resources/application.properties
src/main/resources/logback-spring.xml
src/main/resources/templates/document/personal.html

:tada: [박혜선] logback-spring.xml 생성

---

src/main/resources/templates/home.html

:tada: [김채영] home.html

---

build.gradle
src/main/resources/static/css/home.css
src/main/resources/static/css/include/footer.css
src/main/resources/templates/include/footer.html
src/main/resources/templates/include/layout.html

1. layout.html 구조 수정
- content 하단에만 footer 위치하도록 수정했습니다.
2. footer 디자인 수정
3. build.gradle 주석 처리

:sparkles: [서혜원] layout.html 구조 수정, footer 디자인 수정

---

build.gradle
src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/document/controller/DocumentController.java
src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/member/domain/Member.java
src/main/java/com/fiveLink/linkOffice/member/domain/MemberDto.java
src/main/java/com/fiveLink/linkOffice/member/domain/MemberPermission.java
src/main/java/com/fiveLink/linkOffice/member/domain/MemberPermissionDto.java
src/main/java/com/fiveLink/linkOffice/member/domain/MenuPermission.java
src/main/java/com/fiveLink/linkOffice/member/domain/MenuPermissionDto.java
src/main/java/com/fiveLink/linkOffice/member/domain/PermissionCode.java
src/main/java/com/fiveLink/linkOffice/member/domain/PermissionCodeDto.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/repository/PermissionCodeRepository.java
src/main/java/com/fiveLink/linkOffice/security/config/MyLoginFailureHandler.java
src/main/java/com/fiveLink/linkOffice/security/config/MyLoginSuccessHandler.java
src/main/java/com/fiveLink/linkOffice/security/config/WebSecurityConfig.java
src/main/java/com/fiveLink/linkOffice/security/service/SecurityService.java
src/main/java/com/fiveLink/linkOffice/security/vo/SecurityUser.java
src/main/resources/application.properties
src/main/resources/static/css/login.css
src/main/resources/static/css/pwchange.css
src/main/resources/static/js/pwchange.js
src/main/resources/templates/error.html
src/main/resources/templates/home.html
src/main/resources/templates/include/footer.html
src/main/resources/templates/include/nav.html
src/main/resources/templates/login.html
src/main/resources/templates/member/mypage.html
src/main/resources/templates/pwchange.html

**db 연결**
의존성에서 주석 제거, db 연결
**로그인, 비밀번호 변경 페이지 view 생성**
security 추가 후 permitAll로 설정
**로그인 기능 구현**
로그인 후 home으로 이동
**마이페이지 진입**
home -> 내 정보 클릭 시 mypage.html 들어가는 것까지만

:tada: [전주영] 로그인 기능 추가

---

src/main/java/com/fiveLink/linkOffice/security/config/MyLoginSuccessHandler.java
src/main/java/com/fiveLink/linkOffice/security/config/WebSecurityConfig.java
src/main/resources/static/css/include/header.css
src/main/resources/templates/home.html
src/main/resources/templates/include/header.html

**헤더 로그아웃 추가**
**home.html 권한 별 분리**

:tada: [전주영] 로그아웃 추가 및 home session 분리

---

src/main/resources/static/css/include/nav.css
src/main/resources/static/js/include/nav.js
src/main/resources/templates/include/nav.html

- sidebar 목록 구성
- 드롭 다운 기능 
- css 수정

:sparkles: [김채영] sidebar 수정 및 css

---

src/main/java/com/fiveLink/linkOffice/security/config/WebSecurityConfig.java

**security config**
- 권한 수정 부분 /**  추가했습니다.

:sparkles: [전주영] security config 권한 수정

---

src/main/java/com/fiveLink/linkOffice/security/config/MyLoginSuccessHandler.java
src/main/resources/templates/employee/document/company.html
src/main/resources/templates/employee/document/department.html
src/main/resources/templates/employee/document/personal.html

:sparkle: [박혜선] 문서함 html 수정

---

build.gradle
src/main/java/com/fiveLink/linkOffice/inventory/controller/InventoryViewController.java
src/main/resources/static/css/admin.inventory/list.css
src/main/resources/templates/admin/inventory/list.html

1. 경로 수정 - admin/inventory/list
2. 오타 수정

:sparkles: [김민재] 비품관리 테이블 출력

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/templates/home.html
src/main/resources/templates/include/nav.html

homeController 에서 출력한 MemberDto 의 값을 List<MemberDto>로 출력
- MemberDto에 String position_name, String department_name 출력
- Position, Department / Member와 관계 명시 
- Member에 position, department _ no join column 
( 어제 커밋한..내용에 잇지만.... 감사합니다 )

:sparkles: [전주영] homeController dto 수정 완료

---

src/main/resources/application.properties
src/main/resources/static/css/include/layout.css

:bulb: [서혜원] layout.css 수정

---

.gitignore
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationFunctionController.java
src/main/resources/application.properties
src/main/resources/static/js/admin/vacation/addVacation.js
src/main/resources/templates/admin/vacation/addVacation.html
src/main/resources/templates/include/layout.html

휴가 생성, swal 상태 확인
member 번호 포함 값 입력

:sparkles: [김채영] 휴가 생성(사용자번호) & swal 사용

---

src/main/resources/static/css/employee/member/mypage.css
src/main/resources/templates/employee/member/mypage.html

- mypage.html , css 구조 수정완료 했습니다!

:sparkles: [전주영] 내 정보 mypage.html css 수정완료

---

build.gradle
src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberFileService.java
src/main/resources/application.properties
src/main/resources/static/css/employee/member/digitalname.css
src/main/resources/static/css/employee/member/myedit.css
src/main/resources/static/js/employee/member/digitalname.js
src/main/resources/static/js/employee/member/myedit.js
src/main/resources/templates/employee/member/digitalname.html
src/main/resources/templates/include/nav.html

- 이미지가 있다면 수정 버튼
- 이미지가 없다면 등록 버튼
- 수정 클릭 시 -> 등록 버튼으로 바뀌게끔,,, 
- 등록 클릭 시 -> update 
- 기능 구현 수정중 
- MemberFileService 까지 생성

🎉 [전주영] 전자결재 서명등록 html ,css 생성 기능 수정중

---

src/main/resources/static/js/include/nav.js

:sparkles: [김채영] nav 수정 & 경로 연결

---

build.gradle
src/main/java/com/fiveLink/linkOffice/member/domain/Member.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/java/com/fiveLink/linkOffice/organization/controller/DepartmentController.java
src/main/java/com/fiveLink/linkOffice/organization/domain/DeleteCheckResponse.java
src/main/java/com/fiveLink/linkOffice/organization/repository/DepartmentRepository.java
src/main/java/com/fiveLink/linkOffice/organization/service/DepartmentService.java
src/main/resources/application.properties
src/main/resources/static/css/admin/organization/departmentList.css
src/main/resources/static/css/include/layout.css
src/main/resources/static/js/admin/organization/departmentList.js
src/main/resources/templates/admin/organization/department_list.html
src/main/resources/templates/include/layout.html

**부서명 중복 불가 구현**
- 부서 등록, 수정시 부서명 중복 불가능하도록 함
**하위 부서 생성시 소속 사원 하위 부서로 이동 구현**
- 하위 부서가 없는 상위 부서 소속 사원 존재
-> 이후 하위 부서 생성되는 경우 하위 부서로 이동하도록 구현
**부서 등록, 수정, 삭제 구현 완료**

✨ [서혜원] 부서명 중복 불가, 하위 부서 생성시 사원 소속 변경 구현

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/attendance/controller/AttendanceApiController.java
src/main/java/com/fiveLink/linkOffice/attendance/repository/AttendanceRepository.java
src/main/java/com/fiveLink/linkOffice/attendance/service/AttendanceService.java
src/main/resources/static/css/employee/attendance/attendance.css
src/main/resources/static/js/employee/attendance/attendance.js
src/main/resources/templates/home.html

**출퇴근 기능**
- 로그인 시 homeController에서 출퇴근 여부 조회해서 버튼 활성화 또는 비활성화
- attendance js 수정
- 퇴근 기능 구현 완료

✨  [박혜선] 퇴근 기능 구현 및 버튼 disabled 수정

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/member/domain/MemberDto.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberFileService.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/application.properties
src/main/resources/static/css/employee/member/digitalname.css
src/main/resources/static/js/employee/member/digitalname.js
src/main/resources/templates/employee/member/digitalname.html
src/main/resources/templates/include/nav.html

- 서명등록 성공
- 수정버튼 클릭 시 등록버튼 나오께끔 수정할게요

✨ [전주영] 전자결재 서명등록 등록완료, 수정버튼 클릭시 등록되게끔 수정중

---

src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/java/com/fiveLink/linkOffice/organization/controller/DepartmentController.java
src/main/resources/templates/include/nav.html

:sparkles: [서혜원] 부서관리 memberdto 추가

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/employee/member/digitalname.css
src/main/resources/static/js/employee/member/digitalname.js
src/main/resources/templates/employee/member/digitalname.html

- 이미지 수정하면 원본 이미지 삭제되는거 .... 구현할게요

✨ [전주영] 전자결재 서명 update html , css 수정 및 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberFileService.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java

- 등록 ( update )
- 수정 ( update ) 
수정 시 이미 등록되어있던 이미지 삭제 후 등록

✨ [전주영] 전자결재 서명 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/security/config/MyLoginFailureHandler.java
src/main/resources/static/css/login.css
src/main/resources/templates/login.html

- 아이디, 비밀번호 일치하지 않을 시 오류 메시지 출력

✨ [전주영] 로그인 아이디 / 비밀번호 일치하지 않을 시 오류 메시지 출력

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/document/controller/DocumentViewController.java
src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberFileService.java
src/main/java/com/fiveLink/linkOffice/security/config/MyLoginFailureHandler.java
src/main/java/com/fiveLink/linkOffice/security/config/WebSecurityConfig.java
src/main/resources/static/js/admin/organization/departmentList.js
src/main/resources/static/js/employee/member/digitalname.js
src/main/resources/static/js/employee/member/myedit.js
src/main/resources/templates/employee/member/myedit.html
src/main/resources/templates/include/nav.html

✨ [전주영] 전자서명 url 변경

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/static/js/employee/member/myedit.js
src/main/resources/templates/employee/member/myedit.html
src/main/resources/templates/employee/member/mypage.html

- 데이터베이스에 값 변경 확인
- 값 변경 후 마이페이지, 정보수정 페이지에서 이미지 로드 -> file 설정중

✨ [전주영] 정보수정 수정완료, 이미지 수정시 불러오기중

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/LinkOfficeApplication.java
src/main/java/com/fiveLink/linkOffice/attendance/controller/AttendanceApiController.java
src/main/java/com/fiveLink/linkOffice/attendance/controller/AttendanceViewController.java
src/main/java/com/fiveLink/linkOffice/attendance/service/AttendanceSchedulerService.java
src/main/java/com/fiveLink/linkOffice/attendance/service/AttendanceService.java
src/main/resources/static/css/employee/attendance/attendance.css
src/main/resources/static/js/employee/attendance/attendance.js
src/main/resources/templates/employee/attendance/myAttendance.html

**출퇴근**
- 출퇴근 스케줄러 구현 : AttendanceSchedulerService 생성
- 공휴일 API : AttendanceService에 코드 추가 
- 퇴근 버튼 클릭해도 계속 활성화
- LinkOfficeApplication에 스케줄러 동작 가능을 위한 어노테이션 추가
- attendance js&css 수정 
- HomeController 수정(퇴근 버튼 비활성화 코드 제거)

🎉 [박혜선] 출석 스케줄러 구현&출퇴근 수정

---

src/main/java/com/fiveLink/linkOffice/SpringWebConfig.java
src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/static/css/employee/member/digitalname.css
src/main/resources/static/css/employee/member/myedit.css
src/main/resources/static/css/employee/member/mypage.css
src/main/resources/static/js/employee/member/myedit.js
src/main/resources/templates/employee/member/myedit.html
src/main/resources/templates/employee/member/mypage.html
src/main/resources/templates/home.html

내정보, 정보수정 페이지 기능 구현 및 수정완료
*** 수정 중 ***
전자결재 css

✨ [전주영] 내정보, home, 정보수정 이미지 출력 수정완료

---

src/main/resources/static/css/employee/member/digitalname.css
src/main/resources/templates/employee/member/digitalname.html

✨ [전주영] 전자결재 서명 css 수정완료

---

src/main/java/com/fiveLink/linkOffice/inventory/controller/InventoryViewController.java
src/main/java/com/fiveLink/linkOffice/inventory/repository/InventoryRepository.java
src/main/java/com/fiveLink/linkOffice/inventory/service/InventoryService.java
src/main/resources/logback-spring.xml
src/main/resources/static/css/admin/inventory/list.css
src/main/resources/templates/admin/inventory/list.html

✨ [김민재] 비품관리 부서 세부비품 출력

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/security/config/MyLoginSuccessHandler.java
src/main/java/com/fiveLink/linkOffice/security/config/WebSecurityConfig.java

:sparkles: HomeController, 로그인 경로 수정완료

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/resources/static/js/include/nav.js

:sparkles: home 경로 수정완료

---

src/main/resources/static/css/admin/inventory/list.css
src/main/resources/static/css/datatable.css
src/main/resources/templates/admin/inventory/list.html

1. datatable css 파일 css 경로 아래 추가

🎉 [김민재] 데이터테이블 css 파일 추가

---

src/main/java/com/fiveLink/linkOffice/inventory/domain/Inventory.java
src/main/java/com/fiveLink/linkOffice/inventory/domain/InventoryCategory.java
src/main/java/com/fiveLink/linkOffice/mapper/VacationMapper.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationFunctionController.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationViewController.java
src/main/java/com/fiveLink/linkOffice/vacation/domain/VacationDto.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationService.java
src/main/resources/mappers/vacationMapper.xml
src/main/resources/static/js/admin/vacation/addVacation.js
src/main/resources/templates/admin/vacation/addVacation.html

- 휴가 년차 별 생성
- 동적 생성이 아닌 정적 생성
- 엔티티명 충돌로 인한 엔티티명 정확히 지정

 ✨ [김채영] 휴가 년차별 개수 생성 전반적인 수정

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/security/config/WebSecurityConfig.java
src/main/resources/application.properties
src/main/resources/static/css/employee/member/myedit.css
src/main/resources/static/js/employee/member/myedit.js
src/main/resources/static/js/include/nav.js
src/main/resources/templates/employee/member/myedit.html
src/main/resources/templates/include/header.html

- 비밀번호 입력시 -> 수정페이지 (모달창 닫기) 
-### 헤더 로고 경로 수정

✨ 정보 수정 페이지 비밀번호 모달창 생성 및 헤더 로고 경로 수정

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberFileService.java
src/main/resources/application.properties

:sparkles: 프로필 이미지 수정 시 기존 이미지 삭제

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/resources/static/css/admin/member/create.css
src/main/resources/templates/admin/member/create.html
src/main/resources/templates/include/nav.html

🎉 관리자 사원 등록 페이지 생성 ( html, css ) 구조 수정중

---

src/main/java/com/fiveLink/linkOffice/inventory/controller/InventoryViewController.java
src/main/java/com/fiveLink/linkOffice/inventory/repository/InventoryRepository.java
src/main/resources/static/css/admin/inventory/inventory_create.css
src/main/resources/static/css/admin/inventory/inventory_list.css
src/main/resources/static/css/admin/inventory/list.css
src/main/resources/static/css/datatable.css
src/main/resources/templates/admin/inventory/inventory_create.html
src/main/resources/templates/admin/inventory/inventory_list.html

1. 비품 리스트 출력 완료
2. 비품 등록 페이지 구성
3. 모달창 구성

🎉 [김민재] 비품등록 페이지 생성

---

src/main/java/com/fiveLink/linkOffice/attendance/controller/AttendanceViewController.java
src/main/java/com/fiveLink/linkOffice/attendance/service/AttendanceService.java
src/main/resources/static/css/employee/attendance/myAttendance.css
src/main/resources/static/js/employee/attendance/myAttendance.js
src/main/resources/templates/employee/attendance/myAttendance.html

**근태 조회**
- 근태 조회 페이지 달력 구현
- attendance/myAttendance html, cs, js 수정

✨ [박혜선] 근태 조회 달력 구현

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/resources/static/css/admin/member/create.css
src/main/resources/static/css/employee/member/mypage.css
src/main/resources/static/js/admin/member/create.js
src/main/resources/static/js/employee/member/myedit.js
src/main/resources/static/js/pwchange.js
src/main/resources/templates/admin/member/create.html
src/main/resources/templates/employee/member/mypage.html
src/main/resources/templates/pwchange.html

✨ [전주영] 관리자 사원 등록 페이지 수정중 (html,js,css)

---

src/main/java/com/fiveLink/linkOffice/inventory/controller/InventoryViewController.java
src/main/java/com/fiveLink/linkOffice/inventory/domain/Inventory.java
src/main/java/com/fiveLink/linkOffice/inventory/domain/InventoryDto.java
src/main/java/com/fiveLink/linkOffice/inventory/repository/InventoryRepository.java
src/main/java/com/fiveLink/linkOffice/inventory/service/InventoryService.java
src/main/java/com/fiveLink/linkOffice/member/domain/Member.java
src/main/resources/static/css/admin/inventory/inventory_create.css
src/main/resources/templates/admin/inventory/inventory_create.html

1. 비품 등록 관리자 출력
2.  비품 부서 출력
3.  비품 카테고리 출력

✨ [김민재] 비품등록 관리자,부서 출력

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/java/com/fiveLink/linkOffice/security/config/WebSecurityConfig.java
src/main/resources/static/js/admin/member/create.js

- 사원 생성 완료 
- 사원 목록 조회 후 ( 생성 시 목록으로 넘어가기 ) 
- 암호화 로직 성공 , admin 은 수정중

:sparkles: [전주영] 암호화된 비밀번호

---

src/main/java/com/fiveLink/linkOffice/inventory/controller/InventoryViewController.java
src/main/java/com/fiveLink/linkOffice/inventory/domain/InventoryDto.java
src/main/java/com/fiveLink/linkOffice/inventory/repository/InventoryRepository.java
src/main/java/com/fiveLink/linkOffice/inventory/service/InventoryService.java
src/main/resources/templates/admin/inventory/inventory_create.html

✨ [김민재] 비품등록 정상insert 확인

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/java/com/fiveLink/linkOffice/security/config/WebSecurityConfig.java
src/main/resources/static/css/pwchange.css
src/main/resources/static/js/admin/member/create.js
src/main/resources/static/js/pwchange.js
src/main/resources/templates/pwchange.html

- 정보 입력 후 일치하면 비밀번호 변경
- 변경 후 로그인 페이지로 이동
- 암호화 필요한 페이지 ( 정보수정, 비밀번호 변경 ) 수정 완료

🎉 [전주영] 로그인 전 비밀번호 변경 기능 구현

---

src/main/resources/static/css/login.css
src/main/resources/templates/employee/member/digitalname.html

ori_name 으로 가져온 걸 -> new_name 으로 변경함 ( file 경로가 설정된 걸 불러와서 )

✨ [전주영] 전자결재 서명 경로 변경

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/resources/static/css/admin/member/create.css
src/main/resources/static/css/admin/member/list.css
src/main/resources/static/css/employee/member/myedit.css
src/main/resources/static/css/employee/member/mypage.css
src/main/resources/templates/admin/member/list.html
src/main/resources/templates/employee/member/mypage.html
src/main/resources/templates/include/nav.html

- html 생성
- css 생성 
- 사이드바 -> 경로 확인

🎉 [전주영] 관리자 사원 목록 조회 html 생성 및 css 생성

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/static/css/admin/member/create.css
src/main/resources/static/css/admin/member/list.css
src/main/resources/templates/admin/member/create.html
src/main/resources/templates/admin/member/list.html

- 목록만 조회....
- 검색, 페이징, 정렬 수정중

:sparkles: [전주영] 사원 목록 조회

---

build.gradle
src/main/java/com/fiveLink/linkOffice/mapper/VacationMapper.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationFunctionController.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationViewController.java
src/main/java/com/fiveLink/linkOffice/vacation/domain/VacationType.java
src/main/java/com/fiveLink/linkOffice/vacation/domain/VacationTypeDto.java
src/main/java/com/fiveLink/linkOffice/vacation/repository/VacationTypeRepository.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationService.java
src/main/resources/application.properties
src/main/resources/mappers/vacationMapper.xml
src/main/resources/static/css/admin/vacation/addVacation.css
src/main/resources/static/js/admin/vacation/addVacation.js
src/main/resources/templates/admin/vacation/addVacation.html
src/main/resources/templates/admin/vacation/vacation.html

- 휴가 종류 생성
- 휴가 종류 목록 조회
- 휴가 종류 수정

✨ [김채영] 휴가 종류 목록 & 수정 완료

---

src/main/resources/static/css/admin/member/list.css
src/main/resources/static/js/admin/member/list.js
src/main/resources/templates/admin/member/list.html

:sparkles: [전주영] 사원 목록 조회 css 수정 및 상세 조회 행 클릭

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/application.properties
src/main/resources/static/css/admin/member/detail.css
src/main/resources/static/js/admin/member/detail.js
src/main/resources/templates/admin/member/detail.html

퇴사 처리 ( 상태값 및 퇴사일 업데이트 ) 
- 퇴사 처리 된 사람은 퇴사일에 퇴사일이 나오게끔 수정할게요

:sparkles: [전주영] 사원 상세 조회 퇴사 처리 완료

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/member/domain/MemberDto.java
src/main/resources/static/css/admin/member/detail.css
src/main/resources/static/css/admin/member/list.css
src/main/resources/static/js/admin/member/detail.js
src/main/resources/templates/admin/member/edit.html

- 퇴사일이 없을 경우 퇴사 버튼 및 수정 버튼 
- 퇴사일이 있을 경우 퇴사일 출력
- 수정 버튼 클릭 시 수정 페이지로 이동

:sparkles: [전주영] 사원 상세 조회 시 수정 버튼 추가

---

src/main/java/com/fiveLink/linkOffice/attendance/controller/AttendanceApiController.java
src/main/java/com/fiveLink/linkOffice/attendance/controller/AttendanceViewController.java
src/main/java/com/fiveLink/linkOffice/attendance/repository/AttendanceRepository.java
src/main/java/com/fiveLink/linkOffice/attendance/service/AttendanceService.java
src/main/resources/static/css/employee/attendance/myAttendance.css
src/main/resources/static/js/employee/attendance/attendance.js
src/main/resources/static/js/employee/attendance/myAttendance.js
src/main/resources/templates/employee/attendance/myAttendance.html

**근태 조회 페이지**
- 날짜 설정해서 조회
- 근태 선택해서 조회
- 오름차순 내림차순 정렬 
- myAttendance.html, myAttendance.js, myAttendance.css 수정
- AttendanceViewController, AttendanceService, AttendanceRepository 수정

✨ [박혜선] 근태 조회 페이지 리스트 수정

---

src/main/resources/templates/admin/inventory/inventory_create.html

✨ [김민재] 비품등록 css 수정

---

src/main/java/com/fiveLink/linkOffice/member/domain/Member.java
src/main/resources/static/js/admin/member/create.js
src/main/resources/templates/admin/member/edit.html

- location 변경
- 등록 시 재직 상태 및 권한 상태 null 로 들어가는 문제, member 객체 변경
- insertable 인서트할 때 이 필드를 제외할거다 -> false
@Column(name="member_status", insertable = false, updatable = true)
private Long memberStatus;
@Column(name="member_additional", insertable = false, updatable = true)
private Long memberAdditional;

:sparkles: [전주영] 사원 등록 시 목록으로 이동

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/resources/static/css/admin/member/edit.css
src/main/resources/static/css/employee/member/digitalname.css
src/main/resources/static/css/employee/member/myedit.css
src/main/resources/templates/admin/member/create.html
src/main/resources/templates/admin/member/edit.html
src/main/resources/templates/employee/member/digitalname.html
src/main/resources/templates/employee/member/myedit.html

:sparkles: [전주영] 사원 수정 페이지 css 수정 및 값 불러오기

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/static/css/admin/member/create.css
src/main/resources/static/js/admin/member/create.js
src/main/resources/static/js/admin/member/edit.js
src/main/resources/templates/admin/member/create.html
src/main/resources/templates/admin/member/edit.html

- 내선번호 , 4자리 이하로 가능하게끔 수정
- 관리자 ( 사원 조회, 상세 조회, 수정, 퇴사 완료)

:sparkles: [전주영] 사원 수정 기능 구현 완료

---

src/main/resources/static/css/admin/member/detail.css
src/main/resources/static/css/employee/member/digitalname.css
src/main/resources/static/css/employee/member/myedit.css
src/main/resources/static/css/employee/member/mypage.css
src/main/resources/templates/admin/member/detail.html
src/main/resources/templates/employee/member/digitalname.html
src/main/resources/templates/employee/member/myedit.html
src/main/resources/templates/employee/member/mypage.html

- mypage.html, myedit.html, detail.html, edit.html, ditigtalname.html 
- 주소가 예쁘게 안나와서 css 수정
- 전자서명 버튼 css 수정

:sparkles: [전주영] 관리자 및 사용자 사원 정보 css 수정

---

src/main/java/com/fiveLink/linkOffice/mapper/VacationMapper.java
src/main/java/com/fiveLink/linkOffice/member/domain/Member.java
src/main/java/com/fiveLink/linkOffice/member/domain/MemberDto.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationFunctionController.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationViewController.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationService.java
src/main/resources/mappers/vacationMapper.xml
src/main/resources/static/js/admin/vacation/addVacation.js
src/main/resources/templates/admin/vacation/addVacation.html
src/main/resources/templates/include/nav.html

- 1년미만 재직자 여부 판단
- member관련 컬럼 추가로 인한 정보 수정
- 스케줄링을 통해 매일 00시에 입사일 기준 1년미만 재직자 여부 변경
- 혹은 1년 이상이 될 경우 1년이상으로 상태 변경

:tada: [김채영] 1년 미만 재직자 여부 판단

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/static/css/employee/member/detail.css
src/main/resources/static/js/employee/member/list.js
src/main/resources/templates/admin/member/detail.html
src/main/resources/templates/admin/member/list.html
src/main/resources/templates/employee/member/detail.html
src/main/resources/templates/employee/member/list.html
src/main/resources/templates/employee/member/myedit.html
src/main/resources/templates/employee/member/mypage.html

- 주소록 목록 조회 
-  조회 시 직위가 높은 순으로
- 상태가 재직일 때만
- 상세 조회 
- 사번, 사원명, 입사일, 부서, 직위, 전화번호, 내선번호

:sparkles: [전주영] 주소록 목록 및 상세 조회

---

build.gradle
src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/resources/application.properties
src/main/resources/static/css/pwchange.css
src/main/resources/static/js/pwchange.js
src/main/resources/templates/pwchange.html

- 사번과 주민번호가 일치하지 않을 시 msg 출력
- sweet alert 창이 이상하게 나오는 부분.. 수정
- body에 값이 들어가있어서... 엿슴미다.

:sparkles: [전주영] 비밀번호 변경 시 alert 창 위치 변경

---

src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationViewController.java
src/main/resources/static/css/admin/vacation/vacationStandard.css
src/main/resources/templates/admin/vacation/vacation.html
src/main/resources/templates/include/nav.html

- 휴가 기준 페이지 생성
- 사이드바 경로 생성
- css 적용
-

:tada: [김채영] 휴가 기준 페이지 html&css 생성

---

src/main/java/com/fiveLink/linkOffice/inventory/controller/InventoryViewController.java
src/main/java/com/fiveLink/linkOffice/inventory/repository/InventoryCategoryRepository.java
src/main/java/com/fiveLink/linkOffice/inventory/repository/InventoryRepository.java
src/main/java/com/fiveLink/linkOffice/inventory/service/InventoryService.java
src/main/resources/static/css/admin/inventory/inventory_list.css
src/main/resources/templates/admin/inventory/inventory_create.html
src/main/resources/templates/admin/inventory/inventory_list.html

1. 비품 등록, 비품 목록 기능 구현 끝
2. css 마무리 중

✨ [김민재] 비품등록, 비품목록 기능구현

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/member/domain/MemberDto.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/templates/admin/member/list.html
src/main/resources/templates/employee/member/list.html

:sparkles: [전주영] 관리자 사원 목록 조회 페이징

---

src/main/java/com/fiveLink/linkOffice/member/domain/MemberPermission.java
src/main/java/com/fiveLink/linkOffice/member/domain/MemberPermissionDto.java
src/main/java/com/fiveLink/linkOffice/member/domain/MenuPermission.java
src/main/java/com/fiveLink/linkOffice/member/domain/MenuPermissionDto.java
src/main/java/com/fiveLink/linkOffice/member/repository/PermissionCodeRepository.java
src/main/java/com/fiveLink/linkOffice/permission/controller/PermissionController.java
src/main/java/com/fiveLink/linkOffice/permission/repository/MemberPermissionRepository.java
src/main/java/com/fiveLink/linkOffice/permission/repository/MenuPermissionRepository.java
src/main/java/com/fiveLink/linkOffice/permission/service/PermissionService.java
src/main/resources/static/css/admin/organization/organizationChart.css
src/main/resources/static/js/admin/permission/permissionList.js
src/main/resources/templates/admin/permission/permission.html

**권한 삭제**
- 기능별 권한자 삭제 구현
- fl_menu_permission, fl_member_permission 테이블 status 컬럼 추가

:sparkles: [서혜원] 권한 관리 삭제 기능 구현

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/static/css/employee/member/list.css
src/main/resources/templates/employee/member/list.html

employee/member / list.html, list.css
및 MemberViewController, MemberService, MemberRepository 수정

:sparkles: [전주영] 사용자 주소록 검색, 정렬, 페이징

---

build.gradle
src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/static/css/admin/member/list.css
src/main/resources/static/css/employee/member/list.css
src/main/resources/static/js/admin/member/list.js
src/main/resources/templates/admin/member/list.html

✨ [전주영] 관리자 사원 목록 조회 엑셀 다운로드

---

build.gradle
src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java

:arrow_up: [전주영] 엑셀 다운로드 의존성 추가

---

src/main/java/com/fiveLink/linkOffice/permission/controller/PermissionController.java
src/main/resources/static/css/admin/permission/permission.css
src/main/resources/static/js/admin/permission/permissionList.js
src/main/resources/templates/admin/permission/permission.html

**통합 권한 관리구현 완료**
- 검색
- 삭제
- 페이징
- css 
- permission.css 파일 생성

:sparkles: [서혜원] 권한 관리 검색, 삭제, css 구현 완료

---

src/main/java/com/fiveLink/linkOffice/mapper/VacationMapper.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationFunctionController.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationViewController.java
src/main/java/com/fiveLink/linkOffice/vacation/domain/VacationStandard.java
src/main/java/com/fiveLink/linkOffice/vacation/domain/VacationStandardDto.java
src/main/java/com/fiveLink/linkOffice/vacation/repository/VacationStandardRepository.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationService.java
src/main/resources/mappers/vacationMapper.xml
src/main/resources/static/css/admin/vacation/vacationStandard.css
src/main/resources/static/js/admin/vacation/vacationStandard.js
src/main/resources/templates/admin/vacation/addVacation.html
src/main/resources/templates/admin/vacation/vacation.html

- 휴가 기준 설정
- 지정일 선택시 날짜 입력 활성화
- 둘 중 하나 선택가능하게 제한

:sparkles: [김채영] 휴가 기준 생성 완료

---

build.gradle
src/main/java/com/fiveLink/linkOffice/member/repository/PermissionCodeRepository.java
src/main/resources/application.properties
src/main/resources/static/css/admin/permission/permission.css
src/main/resources/static/js/admin/permission/permissionList.js
src/main/resources/templates/admin/permission/permission.html

**권한 목록**
- 등록일 기준 최신순, 과거순 정렬
- css 수정

✨ [서혜원] 권한 목록 최신순/과거순 구현, css 수정

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/organization/repository/DepartmentRepository.java
src/main/java/com/fiveLink/linkOffice/organization/service/DepartmentService.java
src/main/resources/static/css/employee/member/mypage.css
src/main/resources/static/js/admin/member/detail.js
src/main/resources/templates/employee/member/mypage.html

:sparkles: [전주영] 마이페이지 주소 수정

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/templates/admin/member/list.html

- 검색어 ( 전체, 사번, 사원명, 부서명, 직위명, 상태) 수정
- 검색시 결과가 없다면 " 조회된 목록이 없습니다."
- 페이징 
- 조회했을 때 없으면 아예 안나오도록
- 조회시 1페이지라면 1

:sparkles: [전주영] 관리자 사원 조회 검색어 및 페이징 수정

---

src/main/java/com/fiveLink/linkOffice/mapper/VacationMapper.java
src/main/java/com/fiveLink/linkOffice/member/domain/MemberDto.java
src/main/java/com/fiveLink/linkOffice/vacation/service/AddVacationSchedulerService.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationSchedulerService.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationService.java
src/main/resources/mappers/vacationMapper.xml

- 1년미만, 1년 이상 재직자에 대한 조건
- 입사일 기준, 지정일 기준에 따른 값 설정

:sparkles: [김채영] 휴가 조건들에 따른 제공 개수 제한

---

src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/templates/admin/member/list.html
src/main/resources/templates/employee/member/list.html

- 검색어 ( 전체, 사번, 사원명, 부서명, 직위명, 상태) 수정
- 검색시 결과가 없다면 " 조회된 목록이 없습니다."
- 페이징
- 조회했을 때 없으면 아예 안나오도록
- 조회시 1페이지라면 1

:sparkles: [전주영] 사용자 주소록 페이징 및 검색어 수정

---

src/main/java/com/fiveLink/linkOffice/vacation/service/AddVacationSchedulerService.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationSchedulerService.java
src/main/resources/static/css/admin/vacation/addVacation.css
src/main/resources/static/js/admin/vacation/addVacation.js
src/main/resources/templates/admin/vacation/addVacation.html

:sparkles: [김채영] 휴가페이지 디자인 수정

---

src/main/resources/templates/admin/member/list.html
src/main/resources/templates/employee/member/list.html

- 페이징 부분 첫 1,2 그다음 3개씩 출력
- 정렬, 검색 후 페이징해도 유지되도록

:sparkles: [전주영] 주소록 및 관리자 사원 조회 페이징 및 검색 수정

---

src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/java/com/fiveLink/linkOffice/organization/controller/OrganizationChartController.java
src/main/java/com/fiveLink/linkOffice/organization/controller/PositionController.java
src/main/java/com/fiveLink/linkOffice/permission/controller/PermissionController.java
src/main/resources/static/css/admin/permission/permission.css
src/main/resources/static/js/admin/organization/positionList.js
src/main/resources/static/js/admin/permission/permissionList.js
src/main/resources/templates/admin/permission/permission.html

**조직도**
- 사원 없는 부서 미출력되도록 수정
- 사원 직위 기준 내림차순 정렬
**통합 권한 관리**
- 최신순, 과거순 select box로 수정

[서혜원] 조직도 부서 출력, 사원 정렬/ 권한관리 select box 수정

---

src/main/resources/templates/admin/member/list.html

:sparkles:[전주영] 사원 조회 페이징 수정

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/domain/ApprovalForm.java
src/main/java/com/fiveLink/linkOffice/approval/domain/ApprovalFormDto.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalFormRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalFormService.java
src/main/resources/templates/admin/approval/approval_form.html
src/main/resources/templates/include/nav.html

:sparkles:[전주영] 전자결재 양식함 조회 및 검색, 페이징, 정렬

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/resources/templates/employee/member/mypage.html

- 주소값을 안넣고 다른 정보 수정 시 주소 -> 빈 문자열 들어가는 것
- 수정 !

:sparkles:[전주영] 사원 정보 수정 ( 사용자 ) 시 주소 업데이트

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/domain/ApprovalForm.java
src/main/java/com/fiveLink/linkOffice/approval/domain/ApprovalFormDto.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalFormRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalFormService.java
src/main/resources/static/js/admin/approval/approval_form.js
src/main/resources/templates/admin/approval/approval_detail.html
src/main/resources/templates/admin/approval/approval_form.html

✨[전주영] 관리자 전자결재 양식함 번호 출력

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalFormService.java
src/main/resources/static/css/admin/approval/approval_detail.css
src/main/resources/static/css/admin/approval/approval_edit.css
src/main/resources/templates/admin/approval/approval_detail.html
src/main/resources/templates/admin/approval/approval_edit.html

- 양식함 상세 조회 -> 수정 페이지 이동
- 수정 페이지 에디터 안에 저장된 값 불러오도록 
헷..

:tada: [전주영] 전자결재 양식 상세 수정 에디터

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMessageController.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatMember.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatMemberDto.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatMessage.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatMessageDto.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatRoom.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatRoomDto.java
src/main/java/com/fiveLink/linkOffice/chat/repository/ChatMemberRepository.java
src/main/java/com/fiveLink/linkOffice/chat/repository/ChatMessageRepository.java
src/main/java/com/fiveLink/linkOffice/chat/repository/ChatRoomRepository.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatMemberService.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatMessageService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/java/com/fiveLink/linkOffice/security/config/WebSecurityConfig.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationViewController.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/java/com/fiveLink/linkOffice/webSocket/WebSocketConfig.java
src/main/java/com/fiveLink/linkOffice/webSocket/WebSocketHandler.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html
src/main/resources/templates/include/nav.html

- 웹소켓 연결
- 채팅 메시지 입력 후 디비 삽입 확인
- 사용자에 따른 채팅방 목록과 채팅 내용 출력

 🎉 [김채영] 채팅방 목록과 방 채팅 내용 출력

---

src/main/resources/static/css/admin/approval/approval_detail.css
src/main/resources/static/js/admin/approval/approval_detail.js
src/main/resources/templates/admin/approval/approval_detail.html

- 조회 시 안에 input / textarea 등 막아둠

:sparkles: [전주영] 전자결재 양식함 상세 조회 안에 내용 막기

---

src/main/resources/static/css/admin/approval/approval_detail.css

:sparkles: [전주영] 전자결재 양식함 상세 css 수정

---

src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingController.java
src/main/java/com/fiveLink/linkOffice/meeting/domain/Meeting.java
src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingFileService.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingService.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/permission/controller/PermissionController.java
src/main/java/com/fiveLink/linkOffice/permission/domain/Menu.java
src/main/java/com/fiveLink/linkOffice/permission/repository/MemberPermissionRepository.java
src/main/java/com/fiveLink/linkOffice/permission/service/PermissionService.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationSchedulerService.java
src/main/resources/static/css/admin/meeting/meetingroomList.css
src/main/resources/static/js/admin/meeting/meetingroomList.js
src/main/resources/templates/admin/meeting/meetingroomList.html

**사원 관리 오류 해결**
- fl_member_permission INSERT 삭제
- 권한 등록 후 fl_member 의 member_additional 값 수정 코드 작성
**회의실**
- 관리자 회의실 등록 기능 구현

:tada: [서혜원] 관리자 회의실 등록 구현

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalApiController.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalFormService.java
src/main/resources/static/css/admin/approval/approval_detail.css
src/main/resources/static/css/admin/approval/approval_form.css
src/main/resources/static/js/admin/approval/approval_create.js
src/main/resources/static/js/employee/member/myedit.js
src/main/resources/templates/admin/approval/approval_create.html

- editor, 제목 controller 단 값 확인

:sparkles: [전주영] 전자결재 등록시 controller단 값 확인

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalApiController.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalFormService.java
src/main/resources/static/js/admin/approval/approval_detail.js
src/main/resources/templates/admin/approval/approval_detail.html

:sparkles: [전주영] 전자결재 양식 삭제 상태 업데이트 완료

---

src/main/java/com/fiveLink/linkOffice/notice/controller/NoticeViewController.java
src/main/java/com/fiveLink/linkOffice/notice/service/NoticeService.java
src/main/resources/static/css/admin/notice/notice_create.css
src/main/resources/static/css/datatable.css
src/main/resources/templates/admin/notice/notice_create.html

1. 공지사항 quill editor 적용
2. css 적용

🎉 [김민재] 공지사항 작성 시작

---

src/main/resources/static/js/employee/member/myedit.js

:sparkles: [전주영] 사원 정보 수정 모달 수정

---

src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/static/js/admin/member/edit.js
src/main/resources/templates/admin/approval/approval_detail.html
src/main/resources/templates/admin/member/detail.html
src/main/resources/templates/admin/member/edit.html
src/main/resources/templates/employee/member/detail.html
src/main/resources/templates/employee/member/myedit.html

✨ [전주영] 사원 목록 이동 수정

---

src/main/resources/static/js/admin/approval/approval_create.js

:sparkles: [전주영] 전자결재 양식 등록

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/resources/static/css/admin/approval/approval_create.css
src/main/resources/static/js/admin/approval/approval_create.js
src/main/resources/static/js/admin/approval/approval_detail.js
src/main/resources/static/js/admin/approval/approval_edit.js
src/main/resources/static/js/admin/member/create.js
src/main/resources/static/js/admin/member/detail.js
src/main/resources/static/js/admin/member/edit.js
src/main/resources/static/js/admin/member/list.js
src/main/resources/static/js/employee/member/digitalname.js
src/main/resources/static/js/employee/member/myedit.js
src/main/resources/static/js/pwchange.js
src/main/resources/templates/admin/approval/approval_detail.html

:sparkles: [전주영] 전자결재 양식 목록 클릭 시 모달창 오류 수정

---

build.gradle
src/main/java/com/fiveLink/linkOffice/attendance/service/AttendanceSchedulerService.java
src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingController.java
src/main/java/com/fiveLink/linkOffice/meeting/domain/MeetingDto.java
src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingService.java
src/main/java/com/fiveLink/linkOffice/organization/repository/DepartmentRepository.java
src/main/java/com/fiveLink/linkOffice/organization/service/DepartmentService.java
src/main/java/com/fiveLink/linkOffice/permission/controller/PermissionController.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/application.properties
src/main/resources/static/css/admin/meeting/meetingroomList.css
src/main/resources/static/css/admin/organization/departmentList.css
src/main/resources/static/css/admin/organization/organizationChart.css
src/main/resources/static/css/admin/organization/positionList.css
src/main/resources/static/css/admin/permission/permission.css
src/main/resources/static/css/include/layout.css
src/main/resources/static/js/admin/meeting/meetingroomList.js
src/main/resources/static/js/admin/permission/permissionList.js
src/main/resources/templates/admin/meeting/meetingroomList.html
src/main/resources/templates/admin/organization/department_list.html
src/main/resources/templates/admin/permission/permission.html

**공통 디자인** 
- layout.css : 정렬 select box 디자인, 내부 페이지 제목 h1 디자인 추가
**회의실**
- 관리자 페이지 목록, 등록, 수정 기능 구현

:sparkles: [서혜원] select box, h1 공통 디자인 수정, 회의실 수정 기능 구현

---

src/main/resources/static/css/admin/organization/departmentList.css
src/main/resources/static/css/admin/organization/positionList.css
src/main/resources/static/css/include/layout.css
src/main/resources/templates/admin/organization/department_list.html
src/main/resources/templates/admin/organization/position_list.html

:sparkles: [서혜원] 공통 디자인 수정

---

src/main/java/com/fiveLink/linkOffice/organization/controller/DepartmentController.java
src/main/resources/static/js/admin/organization/departmentList.js
src/main/resources/static/js/admin/organization/positionList.js

:sparkles: [서혜원] 부서, 직위 sweet alert 통일

---

src/main/resources/static/css/admin/organization/departmentList.css
src/main/resources/static/css/admin/organization/positionList.css

:sparkles: [전주영] 조직 관리 css 수정

---

src/main/resources/static/css/admin/vacation/addVacation.css
src/main/resources/static/css/admin/vacation/vacationStandard.css
src/main/resources/templates/admin/vacation/addVacation.html
src/main/resources/templates/admin/vacation/vacation.html

:sparkles: [서혜원] 휴가 css 수정

---

src/main/resources/static/css/login.css
src/main/resources/static/js/admin/approval/approval_create.js
src/main/resources/static/js/admin/approval/approval_detail.js
src/main/resources/static/js/admin/approval/approval_edit.js
src/main/resources/static/js/admin/member/create.js
src/main/resources/static/js/admin/member/detail.js
src/main/resources/static/js/admin/member/edit.js
src/main/resources/static/js/admin/member/list.js
src/main/resources/static/js/admin/vacation/addVacation.js
src/main/resources/static/js/admin/vacation/vacationStandard.js
src/main/resources/static/js/employee/member/digitalname.js
src/main/resources/static/js/employee/member/myedit.js
src/main/resources/static/js/login.js
src/main/resources/static/js/pwchange.js
src/main/resources/templates/login.html

:sparkles: [전주영] js 수정

---

src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationFunctionController.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationService.java
src/main/resources/mappers/vacationMapper.xml
src/main/resources/static/js/admin/vacation/addVacation.js

:sparkles: [김채영] 휴가 중복값 수정

---

src/main/java/com/fiveLink/linkOffice/attendance/controller/AttendanceApiController.java
src/main/java/com/fiveLink/linkOffice/document/controller/DocumentApiController.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFolderService.java
src/main/resources/static/css/employee/document/personal.css
src/main/resources/static/js/employee/attendance/attendance.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/personal.html

**개인 문서함**
- DocumentFolderApiController 생성
- html, css, js 수정
**출퇴근**
- 출퇴근 swal 문구 수정

🎉  [박혜선] 개인 문서함 첫 폴더 생성 기능 구현

---

src/main/java/com/fiveLink/linkOffice/notice/controller/NoticeApiController.java
src/main/java/com/fiveLink/linkOffice/notice/service/NoticeService.java
src/main/resources/static/css/admin/inventory/inventory_create.css
src/main/resources/static/css/admin/inventory/inventory_list.css
src/main/resources/static/css/admin/notice/notice_create.css
src/main/resources/templates/admin/inventory/inventory_create.html
src/main/resources/templates/admin/inventory/inventory_list.html
src/main/resources/templates/admin/notice/notice_create.html
src/main/resources/templates/include/nav.html

✨ [김민재] 공지사항, 비품관리 css 수정

---

src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingController.java
src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingService.java
src/main/resources/static/css/admin/meeting/meetingroomList.css
src/main/resources/static/js/admin/meeting/meetingroomList.js
src/main/resources/templates/admin/meeting/meetingroomList.html
src/main/resources/templates/admin/permission/permission.html

:sparkles: [서혜원] 관리자 회의실 검색 기능 구현

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMessageController.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatMessageDto.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

:sparkles: [김채영] 채팅 작성자 이름 출력

---

src/main/java/com/fiveLink/linkOffice/mapper/VacationMapper.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationFunctionController.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationService.java
src/main/resources/mappers/vacationMapper.xml
src/main/resources/static/js/admin/vacation/addVacation.js

- 휴가 종류 수정 오류 발생 
- 휴가 종류 생성 시 기존에 있는 것 검사 후 생성 실패
- 휴가 종류 수정 시 기존에 있는 것으로 수정할 경우 실패
- 휴가 종류 수정 시 숫자 변경 시 변경 가능하게 수정

:sparkles: [김채영] 휴가 종류 수정 오류 수정

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/admin/meeting/meetingroomList.css
src/main/resources/static/js/admin/meeting/meetingroomList.js

**관리자 회의실**
- 회의실 정보 수정 -> 시간 설정 30분 단위 오류 수정

:bulb: [서혜원] 회의실 수정 시간 30분 단위 오류 수정

---

src/main/resources/static/js/admin/vacation/addVacation.js

:sparkles: [김채영] 휴가 Swal 수정

---

src/main/java/com/fiveLink/linkOffice/inventory/controller/InventoryViewController.java
src/main/java/com/fiveLink/linkOffice/inventory/service/InventoryService.java
src/main/java/com/fiveLink/linkOffice/notice/controller/NoticeApiController.java
src/main/resources/templates/admin/inventory/inventory_create.html
src/main/resources/templates/admin/inventory/inventory_list.html
src/main/resources/templates/admin/notice/notice_create.html

1. sweet alert 수정
2. 비품 관리 등록 관리자 숨김, 목록 관리자 출력

✨ [김민재] sweet 알랏, 관리자 출력 수정

---

build.gradle
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/application.properties
src/main/resources/static/js/admin/chat/chatMessage.js

- 1:1 채팅 성공
- 시간, 이름, 내용 출력 완료

✨ [김채영] 1:1채팅 완료(시간, 이름, 채팅 내용) 출력

---

src/main/resources/mappers/chatMapper.xml
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

:sparkles: [김채영] 1:1채팅 사용자에 따른 div 구분 완료

---

src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js

- 실시간 작성 자에 대한 오류 발생
- 실시간 작성자와 소켓 데이터에서의 작성자가 동일한지 확인 
- div 출력 css 수정

:sparkles: [김채영] 1:1채팅 사용자에 따른 실시간 div구분

---

src/main/java/com/fiveLink/linkOffice/attendance/controller/AttendanceApiController.java
src/main/java/com/fiveLink/linkOffice/attendance/controller/AttendanceViewController.java
src/main/java/com/fiveLink/linkOffice/attendance/domain/Attendance.java
src/main/java/com/fiveLink/linkOffice/attendance/domain/AttendanceDto.java
src/main/java/com/fiveLink/linkOffice/attendance/repository/AttendanceRepository.java
src/main/java/com/fiveLink/linkOffice/attendance/service/AttendanceSchedulerService.java
src/main/java/com/fiveLink/linkOffice/attendance/service/AttendanceService.java
src/main/java/com/fiveLink/linkOffice/document/controller/DocumentApiController.java
src/main/java/com/fiveLink/linkOffice/document/controller/DocumentViewController.java
src/main/java/com/fiveLink/linkOffice/document/domain/DocumentFile.java
src/main/java/com/fiveLink/linkOffice/document/domain/DocumentFileDto.java
src/main/java/com/fiveLink/linkOffice/document/domain/DocumentFolder.java
src/main/java/com/fiveLink/linkOffice/document/domain/DocumentFolderDto.java
src/main/java/com/fiveLink/linkOffice/document/repository/DocumentFileRepository.java
src/main/java/com/fiveLink/linkOffice/document/repository/DocumentFolderRepository.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFileService.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFolderService.java
src/main/java/com/fiveLink/linkOffice/organization/repository/DepartmentRepository.java
src/main/resources/static/js/employee/document/personal.js

**출근**
- Attendance, AttendanceDto joinColumn 수정 및 컨트롤러, 서비스, 레포지토리 수정
**문서함**
- DocumentFolder, DocumentFolderDto joinColumn 수정 및 컨트롤러, 서비스, 레포지토리 수정
- DocumentFile, DocumentFileDto  joinColumn 수정 및 컨트롤러, 서비스, 레포지토리 수정
- DepartmentRepository에 **findByDepartmentNo** 추가

✨ [박혜선] attendance, folder, file 객체 joinColumn 수정

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/member/domain/Member.java
src/main/java/com/fiveLink/linkOffice/security/CustomUserResignedException.java
src/main/java/com/fiveLink/linkOffice/security/config/MyLoginFailureHandler.java
src/main/java/com/fiveLink/linkOffice/security/service/SecurityService.java
src/main/resources/static/css/login.css
src/main/resources/templates/login.html

- 퇴사 사원 
- 없는 사원
- 오류 발생
- 나도 오류 남

:tada: 퇴사 사원, 없는 사원 로그인 시 Exception 발생

---

src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingController.java
src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingReservationController.java
src/main/java/com/fiveLink/linkOffice/meeting/domain/MeetingReservation.java
src/main/java/com/fiveLink/linkOffice/meeting/domain/MeetingReservationDto.java
src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingReservationRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingReservationService.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingService.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/templates/employee/meeting/meetingReservation.html
src/main/resources/templates/include/nav.html

**사원 회의실**
- 예약 페이지 디자인
- 달력 , 회의실 정보, 날짜별 예약 현황

:sparkles: [서혜원] 사원 회의실 예약 정보 출력

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_detail.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_create.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html
src/main/resources/templates/include/nav.html

:sparkles: [전주영] list 경로 수정

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/resources/templates/include/nav.html

:sparkles: [전주영] 휴가 신청하기 경로 수정

---

src/main/java/com/fiveLink/linkOffice/attendance/controller/AttendanceViewController.java
src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalRepository.java
src/main/resources/static/js/employee/attendance/myAttendance.js
src/main/resources/templates/employee/attendance/myAttendance.html

**근태 조회**
- 근태 휴가 반영 출력
- VacationApprovalRepository 휴가 조회를 위한 코드 추가

✨  [박혜선] 근태 조회 휴가 출력

---

src/main/java/com/fiveLink/linkOffice/notice/controller/NoticeViewController.java
src/main/java/com/fiveLink/linkOffice/notice/repository/NoticeRepository.java
src/main/java/com/fiveLink/linkOffice/notice/service/NoticeService.java
src/main/resources/templates/admin/notice/notice_list.html

1. 선택 상황에 맞는 페이징 [중요]상단 고정
2. [중요] 표시

✨ [김민재] 공지사항페이징, [중요]표시

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/vacation/repository/VacationTypeRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_list.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_list.html

:sparkles: [전주영] 휴가 결재 등록 ( 문서만 ) 

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMemberController.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatRoom.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatRoomDto.java
src/main/java/com/fiveLink/linkOffice/chat/repository/ChatRoomRepository.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatMemberService.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatRoomService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationService.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/js/admin/chat/chatMember.js
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 콘솔 테스트 삭제
- 1:1 채팅방 생성 
(현재, 개인 채팅방 생성 후 알림 창 안되는 오류 발생 ㅠ)

🎉 [김채영] 채팅 1:1채팅방 생성

---

src/main/java/com/fiveLink/linkOffice/notice/controller/NoticeViewController.java
src/main/java/com/fiveLink/linkOffice/notice/service/NoticeService.java
src/main/resources/static/css/admin/inventory/inventory_list.css
src/main/resources/static/css/admin/notice/notice_list.css
src/main/resources/templates/admin/notice/notice_detail.html
src/main/resources/templates/admin/notice/notice_list.html
src/main/resources/templates/include/nav.html

1. 공지사항 목록 마무리
2. 공지사항 세부항목 진행중

✨ [김민재] 공지사상 세부사항 진행중

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentViewController.java
src/main/java/com/fiveLink/linkOffice/document/repository/DocumentFileRepository.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFileService.java
src/main/resources/static/css/employee/document/personal.css
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/personal.html

✨  [박혜선] 개인 문서함 용량 출력

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApproval.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalFile.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalFileDto.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalFileRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalFileService.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/application.properties
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_create.html

:sparkles: [전주영] 휴가 결재 등록 문서 및 파일

---

build.gradle
src/main/java/com/fiveLink/linkOffice/meeting/domain/MeetingReservationDto.java
src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingReservationRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingReservationService.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/resources/application.properties
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/include/layout.css
src/main/resources/static/js/admin/organization/organizationChart.js
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/templates/employee/meeting/meetingReservation.html

:sparkles: [서혜원] 사원 회의실 예약 디자인 수정

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalDto.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalFileRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html

- 신청 문서 조회
- 등록된 파일 조회 
- 파일 다운로드

:sparkles: [전주영] 휴가 결재 신청 조회 등록 문서 및 파일 출력

---

src/main/resources/static/css/admin/notice/notice_detail.css
src/main/resources/templates/admin/notice/notice_detail.html

✨ [김민재] 공지사항 세부사항 css 수정

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentApiController.java
src/main/java/com/fiveLink/linkOffice/document/controller/DocumentViewController.java
src/main/java/com/fiveLink/linkOffice/document/domain/DocumentFileDto.java
src/main/java/com/fiveLink/linkOffice/document/repository/DocumentFileRepository.java
src/main/java/com/fiveLink/linkOffice/document/repository/DocumentFolderRepository.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFileService.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFolderService.java
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/department.html

**문서함**
- 개인 문서함 js 일부 수정
- 부서 문서함 html, css, js 수정
- Document controller, service, repository, dto 수정

✨  [박혜선] 부서 문서함 폴더&파일 목록 출력 기능 구현

---

src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingReservationController.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/java/com/fiveLink/linkOffice/organization/controller/OrganizationChartController.java
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/templates/employee/meeting/meetingReservation.html

**사원 회의실**
- 날짜, 회의실 선택에 따른 예약 가능 시간대 변경

:sparkles: [서혜원] 사원 회의실 예약 조건 구현 중

---

src/main/resources/static/css/employee/organization/approval.css
src/main/resources/static/js/employee/organization/approval.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_create.html

:sparkles: [전주영] 휴가결재 조직도 화면단 출력

---

src/main/resources/static/css/employee/organization/approval.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_create.css
src/main/resources/static/js/employee/organization/approval.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_create.html

- 히든으로 번호 가져오기 (vacationapproval_create.html)
- 휴가 결재 흐름 dto 및 entity  생성한 후 조인해서 값 넣어주기 (해보께요)

:sparkles: [전주영] 휴가결재 결재자 번호 가져오기

---

src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingReservationController.java
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/js/admin/organization/organizationChart.js
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/templates/employee/meeting/meetingReservation.html

:sparkles: [서혜원] 사원 회의실 예약 전송 확인

---

src/main/java/com/fiveLink/linkOffice/member/domain/Member.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApproval.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalFlow.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalFlowDto.java

:tada: [전주영] 휴가 결재자 흐름 dto, Entity 생성

---

build.gradle
src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMessageController.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/application.properties
src/main/resources/static/js/admin/chat/chatMember.js
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 웹소켓이 두번 작동되는 오류 수정
- 실시간으로 채팅목록 띄우기 구현
- 소켓 url오류 수정

💡 [김채영] 채팅방 생성시 발생한 오류 수정 완료

---

src/main/java/com/fiveLink/linkOffice/chat/controller/chatOrganizationController.java
src/main/resources/templates/admin/organization/organizationChart.html

:bulb: [김채영] 채팅방 생성시 발생한 오류 수정 완료

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApproval.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalDto.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalFlow.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalFlowRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java

- 흐름 데이터베이스 값 추가 확인 ( 결재선 지정 후 등록하면 ) 
- VacationApprovalFlowRepository 생성
- VacationApproval 과 VacationApprovalFlow 엔티티 관계 수정
- 파일 있을 때 없을 때 두 가지 상황으로 나누어서 save

:sparkles: [전주영] 휴가 결재 흐름 데이터베이스 값 추가 확인

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMemberController.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatRoomService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/js/admin/chat/chatMember.js
src/main/resources/static/js/admin/chat/chatMessage.js

- 채팅방 생성 시 필요했던 controller, js 통합으로 인해 나머지 주석처리
- 채팅방 생성 후 실시간 목록 정렬 수정(생긴 채팅방이 맨 위로 정렬)
- 채팅방 생성 후 이름 + 부서로 채팅방 이름 지정(DB저장)

✨ [김채영] 채팅방 생성후 이름+부서로 채팅방 이름 지정

---

src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/static/js/admin/chat/chatMessage.js

- 채팅방 생성 시 상대방 채팅방 목록 업데이트 부분 
- 생성과 동시에 업데이트보단 글 전송과 동시에 노출하는 쪽으로 구성

:sparkles: [김채영] 채팅방 생성 후 메시지 전송을 통해 채팅방 목록 업데이트

---

src/main/resources/static/js/admin/chat/chatMessage.js

- 채팅 url 이동 시, 오른쪽 구역(메시지 확인 및 전송)에 목록 제일 첫 번째 채팅방 내용 출력

:sparkles: [김채영] 채팅 url 이동 시, 목록 상단의 내용 출력

---

src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingReservationController.java
src/main/java/com/fiveLink/linkOffice/meeting/domain/MeetingReservationDto.java
src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingParticipantRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingReservationRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingReservationService.java
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/employee/meeting/myMeetingReservation.css
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/templates/employee/meeting/meetingReservation.html
src/main/resources/templates/employee/meeting/myMeetingReservation.html
src/main/resources/templates/include/nav.html

**사원 회의실**
- 개인 회의실 예약 목록 조회
- 페이징, 회의실명 필터링, 목적 검색 구현

✨ [서혜원] 개인 예약 목록 조회

---

build.gradle
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalFileRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalFlowRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/application.properties

- 신청한 멤버의 번호가 결재 흐름으로 저장이 되는 현상 수정

:sparkles: [전주영] 휴가 결재 흐름 데이터베이스 멤버값 수정

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/static/js/employee/vacationapproval/vacationapproval_detail.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_list.html

- 휴가 결재 상세 조회 -> 기안 취소 기능 구현 완료

:sparkles: [전주영] 휴가 결재 상세 조회 및 기안 취소

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/resources/static/js/employee/member/digitalname.js
src/main/resources/static/js/employee/member/myedit.js
src/main/resources/templates/include/nav.html

:sparkles: [전주영] 마이페이지 url member_no 제거

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/resources/static/js/employee/approval/approval_history_list.css
src/main/resources/templates/employee/approval/approval_history_list.html
src/main/resources/templates/employee/approval/approval_progress_list.html
src/main/resources/templates/employee/approval/approval_references_list.html
src/main/resources/templates/employee/approval/approval_reject_list.html
src/main/resources/templates/include/nav.html

- 수신함 
- 내역, 참조함 html 생성
- 상신함
- 진행, 반려함 html 생성
-url 이동

:tada: [전주영] 전자결재 수신함 상신함 html 생성

---

src/main/java/com/fiveLink/linkOffice/chat/service/ChatMemberService.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatRoomService.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 그룹 채팅방 생성 2명 이상 선택 시 그룹명 받기
-  그룹명 입력받고 채팅방 생성

:tada: [김채영] 그룹채팅방 생성 & 그룹채팅방명 입력

---

src/main/resources/application.properties
src/main/resources/static/js/admin/chat/chatMessage.js

- 그룹 채팅방 생성시 인원수 제한 수정
- 그룹 채팅방 생성 후, 실시간 메시지 전송 확인

🎉 [김채영] 그룹채팅방 실시간 메시지 입력

---

src/main/resources/static/css/admin/chat/chat.css

:sparkles: [김채영] 그룹 채팅명 css 수정

---

src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 채팅 페이지 진입 시 전반적인 css 수정 
- 스크롤 활성화

:sparkles: [김채영] 채팅 페이지 전반적 css 수정

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalFlowRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/static/css/employee/approval/approval_history_list.css
src/main/resources/static/css/employee/approval/approval_references_list.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js
src/main/resources/templates/employee/approval/approval_history_list.html
src/main/resources/templates/employee/approval/approval_references_list.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_create.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_list.html

:sparkles: [전주영] 전자결재 수신함 목록 조회 및 정렬, 검색 페이징 (휴가결재만)

---

src/main/resources/static/css/admin/approval/approval_form.css
src/main/resources/static/css/admin/member/list.css
src/main/resources/static/css/employee/approval/approval_history_list.css
src/main/resources/static/css/employee/approval/approval_references_list.css
src/main/resources/static/css/employee/member/list.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_list.css
src/main/resources/templates/admin/approval/approval_form.html
src/main/resources/templates/admin/member/list.html
src/main/resources/templates/employee/approval/approval_history_list.html
src/main/resources/templates/employee/approval/approval_references_list.html
src/main/resources/templates/employee/member/list.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_list.html

- 정렬과 검색 form 합치기 
- 전자결재, 휴가결재, 사원 목록 수정 완료

:sparkles: [전주영] 사원 목록 조회 및 결재 목록 조회 list 검색 정렬 수정

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMemberController.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatMemberService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 현재 채팅하고 있는 채팅방 이름 채팅 메시지 부분에 출력
- 채팅 메시지 전반적 css 수정

:sparkles: [김채영] 채팅메시지 입력 부분 css 수정 & 채팅방 이름 출력

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/resources/application.properties
src/main/resources/static/css/employee/vacationapproval/vacationapproval_edit.css
src/main/resources/static/js/employee/vacationapproval/vacationapproval_edit.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_edit.html
src/main/resources/templates/home.html

- html 생성
- 기본 값 불러오기
- 내정보 경로 수정

:sparkles: [전주영] 휴가 결재 수정 html 생성 및 값 불러오기

---

src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingReservationController.java
src/main/resources/application.properties
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/employee/meeting/reservationDetail.css
src/main/resources/static/js/employee/meeting/reservationDetail.js
src/main/resources/templates/employee/meeting/reservationDetail.html

**사원 회의실**
- 본인이 예약자인 경우
- 회의실 예약 정보 수정 
- 참여자 수정 구현 중

:sparkles: [서혜원] 회의실 예약 정보 수정 구현 중

---

src/main/java/com/fiveLink/linkOffice/notice/controller/NoticeApiController.java
src/main/java/com/fiveLink/linkOffice/notice/service/FileService.java
src/main/resources/static/css/admin/notice/notice_update.css
src/main/resources/templates/admin/notice/notice_detail.html
src/main/resources/templates/admin/notice/notice_update.html

✨ [김민재] 공지수정 삭제 버튼 기능 구현

---

src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

:sparkles: [김채영] 채팅방 목록 자동완성 검색

---

build.gradle
src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingReservationController.java
src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingParticipantRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingParticipantService.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingReservationService.java
src/main/resources/application.properties
src/main/resources/static/js/employee/meeting/reservationDetail.js
src/main/resources/templates/employee/meeting/meetingReservation.html
src/main/resources/templates/employee/meeting/reservationDetail.html

**사원 회의실**
- 예약 정보 수정 기능 구현 완료
- 회의실명, 날짜, 시간, 목적, 참여자 정보 수정

:sparkles: [서혜원] 회의실 예약 정보 수정 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/member/domain/Member.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java
src/main/java/com/fiveLink/linkOffice/notice/controller/NoticeViewController.java
src/main/java/com/fiveLink/linkOffice/notice/service/NoticeService.java
src/main/java/com/fiveLink/linkOffice/survey/controller/SurveyApiController.java
src/main/java/com/fiveLink/linkOffice/survey/controller/SurveyViewController.java
src/main/java/com/fiveLink/linkOffice/survey/domain/Survey.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyDto.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyParticipant.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyParticipantDto.java
src/main/java/com/fiveLink/linkOffice/survey/repository/SurveyRepository.java
src/main/java/com/fiveLink/linkOffice/survey/service/SurveyService.java
src/main/resources/static/css/employee/survey/survey_my_list.css
src/main/resources/templates/admin/notice/notice_list.html
src/main/resources/templates/employee/survey/survey_my_list.html

🎉 [김민재] 설문조사 내가 만든 설문 목록 출력

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMemberController.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatMemberService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 채팅 방 목록 자동완성 검색 구조 수정
- css와 동작 js 수정
- 채팅방 이름 불러오는  방법 수정

:sparkles: [김채영] 채팅방 목록 자동 완성 검색 css & js 수정

---

src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 채팅 메시지 미 입력시 버튼 비활성화
- 디비에 빈 메시지 내용 들어가는 것 제한 
- 채팅 시간 css 통일

:sparkles: [김채영] 채팅메시지 내용 제한 수정

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentApiController.java
src/main/java/com/fiveLink/linkOffice/document/repository/DocumentFolderRepository.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFolderService.java
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/company.html
src/main/resources/templates/employee/document/department.html
src/main/resources/templates/employee/document/personal.html

**문서함 폴더 생성**
- 개인 문서함, 부서 문서함, 사내 문서함 폴더 생성 기능 구현으로 html, js, css, DocumentApiController, DocumentService, DocumentRepository 수정 및 코드 추가

🎉 [박혜선] 문서함 폴더 생성 기능 구현

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalFileRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalFlowRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalFileService.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/static/css/employee/vacationapproval/vacationapproval_edit.css
src/main/resources/static/js/employee/vacationapproval/approval_edit.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_edit.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_edit.html

- 수정 시 ( 파일이 없을 때 ) 
- 파일 추가 
- 수정 시 ( 파일이 있을 때 )
- 파일 삭제 후 파일 추가
- 수정 시 ( 결재자 미지정 )
- 결재선을 다시 지정 안할 시, 기존 값 유지
- 수정 시 ( 결재자 지정 ) 
- 결재선 다시 지정 시 , 기존 값 삭제 후 insert
✨ .... 제송합니닷

✨ [전주영] 휴가 결재 수정 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/resources/static/js/employee/approval/approval_history_list.css
src/main/resources/static/js/employee/approval/approval_history_list.js
src/main/resources/templates/employee/approval/approval_history_detail.html
src/main/resources/templates/employee/approval/approval_history_list.html

- 목록에서 선택 시 상세 조회 
- 상세 내역 출력
- 날짜 조회 format

:tada: [전주영] 전자결재 결재 내역함 상세 조회

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalFlowRepository.java
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html

- 상태가 진행 전일 경우 조회 불가
- 결재 차례가 오면 출력

:sparkles: [전주영] 전자결재 내역함 결재 상태가 진행 전일 때는미조회

---

src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 채팅 목록 구성 수정
- 채팅방 선택후 목록 hover 처리 
- 채팅방 개인 설정을 위한 드롭 메뉴 구성

🎉 [김채영] 채팅방 설정 드롭바

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/resources/static/css/employee/approval/approval_history_detail.css
src/main/resources/templates/employee/approval/approval_history_detail.html

- 로그인한 멤버 번호와 결재, 합의 번호와 같다면 승인 및 반려버튼 출력
- 결재 날짜 출력 ( 없으면 미출력 )

:sparkles: [전주영] 전자결재 내역함 상세 조회 시 반려 및 승인 버튼 출력

---

src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 설정에서 그룹 명 수정 버튼 눌러 모달창 오픈
- 모달창에서 입력된 수정 그룹명을 웹소켓 서버로 넘기기

:tada: [김채영] 그룹 채팅방 이름 수정 기능

---

src/main/java/com/fiveLink/linkOffice/member/domain/Member.java
src/main/java/com/fiveLink/linkOffice/survey/controller/SurveyViewController.java
src/main/java/com/fiveLink/linkOffice/survey/domain/Survey.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyParticipant.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyParticipantDto.java
src/main/java/com/fiveLink/linkOffice/survey/repository/SurveyRepository.java
src/main/java/com/fiveLink/linkOffice/survey/service/SurveyService.java
src/main/resources/static/css/employee/survey/survey_end_list.css
src/main/resources/templates/employee/survey/survey_end_list.html
src/main/resources/templates/employee/survey/survey_my_list.html

1. 내가 만든 설문 조건식 추가
2. 마감된 설문 목록 출력

✨ [김민재] 마감된 설문 목록 출력

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/admin/approval/approval_form.css
src/main/resources/static/css/employee/approval/approval_history_list.css
src/main/resources/static/css/employee/approval/approval_references_list.css
src/main/resources/static/css/employee/member/list.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_list.css
src/main/resources/templates/employee/vacationapproval/vacationapproval_create.html
src/main/resources/templates/include/nav.html

- 전자결재 수신함 목록 
- 양식 목록 
- 사원 조회
- 주소록
- 전자결재 양식 등록 /  양식함 위치 변경
- 휴가 신청하기  -> 신청

:sparkles: [전주영] 전자결재 및 사원 목록 조회 시 정렬 select css 수정

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalApiController.java
src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalFlowRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/static/js/employee/approval/approval_history_detail.js

** 휴가결재 승인 **
- 첫번째 결재자 승인 후 다음 결재자 승인 버튼 생성
- 결재 흐름 순서 업데이트 확인
- 다음 결재자가 없다면 문서 업데이트 
- 결재완료 시 등록한 전자서명 출력되게 해야함
- css 수정 중

:sparkles: [전주영] 휴가결재 승인 db 값 확인

---

src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

:sparkles: [김채영] 그룹 채팅방 이름 css와 모달 js 수정

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalFlowDto.java
src/main/resources/templates/employee/approval/approval_history_detail.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html

:sparkles: [전주영] 결재 시 전자서명 출력 / 승인 및 반려 버튼 미출력

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html

- 기안자 다음 결재자가 진행중이 아닐 경우 수정 버튼 미출력

:sparkles: [전주영] 휴가결재 기안자 다음 결재자가 승인 시 수정버튼 미출력

---

src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingReservationController.java
src/main/resources/static/css/admin/meeting/meetingReservationList.css
src/main/resources/static/js/admin/meeting/meetingReservationList.js
src/main/resources/templates/admin/meeting/meetingReservationList.html
src/main/resources/templates/employee/meeting/myMeetingReservation.html

:bulb: [서혜원] 회의실명 검색어 유지 수정

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalApiController.java
src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/repository/MemberRepository.java

:sparkles: [전주영] approval controller , member controller / repository 주석 수정

---

build.gradle
src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMemberController.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatMemberService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/resources/application.properties
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 채팅방 안에 수정과 초대와 같이 그룹 채팅방에서 사용할 기능을 권한 부여
- 개인 채팅방은 기본 나가기, 알림, 고정과 같은 기능을 부여

 ✨ [김채영] 그룹 채팅과 개인 채팅 설정 권한 구분

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/static/js/employee/meeting/reservationDetail.js

**회의실**
- 예약 : 오늘 현재 시간 이전 예약 현황 테이블 ursor: not-allowed; 추가
- 예약, 예약 수정 : 오늘 현재 시간 이전 시간 select box 비활성화

:sparkles: [서혜원] 현재 시간 이전 예약 불가 구현

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentFileController.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFileService.java
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/company.html
src/main/resources/templates/employee/document/department.html
src/main/resources/templates/employee/document/personal.html

**문서함 파일 업로드**
- 각 문서함 파일 업로드 기능 구현 완료
- DocumentFileController.java 생성
- 개인, 부서, 사내 문서함 js, html, css 수정

🎉  [박혜선] 문서함 파일 업로드 기능 구현 완료

---

src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js

:sparkles: [김채영] 채팅 메시지 css 수정

---

src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingReservationController.java
src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingReservationRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingReservationService.java
src/main/resources/application.properties
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/static/js/employee/meeting/reservationDetail.js
src/main/resources/templates/admin/meeting/meetingReservationList.html
src/main/resources/templates/admin/meeting/meetingroomList.html
src/main/resources/templates/employee/meeting/reservationDetail.html

**회의실**
- css 수정
- 예약 정보 수정 -> 조직도 모달 정보 수정

:sparkles: [서혜원] 회의실 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentFileController.java
src/main/java/com/fiveLink/linkOffice/document/repository/DocumentFileRepository.java
src/main/resources/application.properties
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js

**문서함 파일 삭제**
- 개인, 부서, 사내 문서함 파일 삭제 기능 구현 완료
- application.properties 문서함 파일 용량 코드(multipart.max-file-size, multipart.max-request-size)2줄 추가

🎉  [박혜선] 문서함 파일 삭제 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentFileController.java
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/company.html
src/main/resources/templates/employee/document/department.html
src/main/resources/templates/employee/document/personal.html

**문서함**
- 개인, 부서, 사내 문서함 파일 선택 삭제 기능 구현 완료

🎉  [박혜선] 문서함 파일 선택 삭제 기능 구현

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/resources/static/css/admin/approval/approval_form.css
src/main/resources/static/css/admin/member/list.css
src/main/resources/static/css/employee/approval/approval_history_list.css
src/main/resources/static/css/employee/approval/approval_references_list.css
src/main/resources/static/css/employee/member/list.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_list.css
src/main/resources/static/js/admin/member/create.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html

:sparkles: [전주영] 사원 본인 휴가결재 기안취소 버튼

---

src/main/resources/static/css/employee/approval/approval_history_detail.css
src/main/resources/templates/employee/approval/approval_history_detail.html

- 그 다음 결재자가 승인을 하지 않은 상태일 때 (진행중)
- 본인이 승인 완료 상태일 때

:sparkles: [전주영] 결재자 view 승인 취소 버튼

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/static/css/employee/approval/approval_history_detail.css
src/main/resources/static/js/employee/approval/approval_history_detail.js
src/main/resources/templates/employee/approval/approval_history_detail.html

- 승인 취소 시 그 다음 결재자 와 나의 진행 상태 변경

:sparkles: [전주영] 결재자 승인 취소 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMemberController.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatMemberService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 채팅 메시지 입력 오류 수정
- 그룹 채팅 사용자 초대 기능 구현

✨ [김채영] 그룹 채팅 멤버 초대

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/resources/static/css/employee/approval/approval_history_detail.css
src/main/resources/static/css/employee/approval/approval_references_detail.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/static/js/employee/approval/approval_references_list.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_detail.js
src/main/resources/templates/employee/approval/approval_history_detail.html
src/main/resources/templates/employee/approval/approval_references_detail.html
src/main/resources/templates/employee/approval/approval_references_list.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html

:sparkles: [전주영] 휴가 결재 참조함 상세 조회

---

src/main/java/com/fiveLink/linkOffice/document/service/DocumentFileService.java
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/company.html
src/main/resources/templates/employee/document/department.html
src/main/resources/templates/employee/document/personal.html

**문서함**
- 파일 형식 제한
- 문서함 js 파일 출력 함수 수정
- html 파일 목록 출력 테이블 width 수정

✨ [박혜선] 파일 형식 제한&파일 목록 출력 수정

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/static/css/employee/approval/approval_history_detail.css
src/main/resources/static/css/employee/approval/approval_references_detail.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/static/js/employee/approval/approval_history_detail.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_detail.js
src/main/resources/templates/employee/approval/approval_history_detail.html
src/main/resources/templates/employee/approval/approval_references_detail.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html

:sparkles: [전주영] 반려 사유 작성 기능 구현 완료

---

src/main/resources/application.properties
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js

🎉 [박혜선] 개인 문서함 검색 기능 구현

---

build.gradle
src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleController.java
src/main/java/com/fiveLink/linkOffice/schedule/repository/ScheduleRepository.java
src/main/java/com/fiveLink/linkOffice/schedule/service/ScheduleCategoryService.java
src/main/resources/application.properties
src/main/resources/static/css/admin/schedule/scheduleCategory.css
src/main/resources/static/js/admin/schedule/scheduleCategory.js
src/main/resources/templates/admin/permission/permission.html
src/main/resources/templates/admin/schedule/scheduleCategory.html

**관리자 일정**
- 카테고리 등록, 수정, 삭제
- 해당 카테고리로 등록된 일정 존재하는 경우 삭제 불가

:sparkles: [서혜원] 관리자 일정 카테고리 등록, 수정, 삭제 구현

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalFormRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalFormService.java
src/main/resources/static/css/employee/approval/approval.css
src/main/resources/static/css/employee/approval/approval_create.css
src/main/resources/static/js/employee/approval/approval.js
src/main/resources/static/js/employee/approval/approval_create.js
src/main/resources/templates/employee/approval/approval_create.html
src/main/resources/templates/include/nav.html

- html 생성
-  css 생성
- 에디터 불러오기
- 양식 불러오기 (번호값)

:tada:[전주영] 전자결재 작성 html 및 css 생성

---

src/main/java/com/fiveLink/linkOffice/notice/service/FileService.java
src/main/java/com/fiveLink/linkOffice/survey/controller/SurveyViewController.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyAnswerOption.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyAnswerOptionDto.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyOption.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyOptionDto.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyQuestion.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyQuestionDto.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyText.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyTextDto.java
src/main/java/com/fiveLink/linkOffice/survey/repository/SurveyRepository.java
src/main/java/com/fiveLink/linkOffice/survey/service/SurveyService.java
src/main/resources/static/css/admin/notice/notice_list.css
src/main/resources/templates/admin/notice/notice_create.html
src/main/resources/templates/admin/notice/notice_list.html
src/main/resources/templates/admin/notice/notice_update.html
src/main/resources/templates/employee/survey/survey_question_detail.html

✨ [김민재] 설문 문항 출력중

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalApiController.java
src/main/java/com/fiveLink/linkOffice/approval/domain/Approval.java
src/main/java/com/fiveLink/linkOffice/approval/domain/ApprovalDto.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalFileRepository.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalFlowRepository.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalFileService.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/resources/static/js/employee/approval/approval_create.js
src/main/resources/templates/employee/approval/approval_create.html

:sparkles: [전주영] 전자결재 등록 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/domain/ApprovalDto.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalRepository.java
src/main/resources/static/css/employee/approval/approval_progress_list.css
src/main/resources/static/css/employee/approval/approval_reject_list.css
src/main/resources/templates/employee/approval/approval_progress_list.html
src/main/resources/templates/employee/approval/approval_reject_list.html

- 상신함 (상태에 따라서 출력 목록 다르게)
- 결재 진행함 페이징, 검색, 정렬 
- 결재 반려함 페이징, 검색, 정렬

:sparkles: [전주영] 전자결재 상신함 목록 조회 및 정렬, 검색

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalApiController.java
src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/domain/ApprovalDto.java
src/main/java/com/fiveLink/linkOffice/approval/domain/ApprovalFlowDto.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalFileRepository.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalFlowRepository.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/java/com/fiveLink/linkOffice/security/config/MyLoginSuccessHandler.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/static/css/employee/approval/approval_progress_detail.css
src/main/resources/static/css/employee/approval/approval_reject_detail.css
src/main/resources/static/js/employee/approval/approval_progress_detail.js
src/main/resources/static/js/employee/approval/approval_progress_list.js
src/main/resources/static/js/employee/approval/approval_reject_list.js
src/main/resources/templates/employee/approval/approval_progress_detail.html
src/main/resources/templates/employee/approval/approval_progress_list.html
src/main/resources/templates/employee/approval/approval_reject_detail.html
src/main/resources/templates/employee/approval/approval_reject_list.html

- 로그인 유지 시 session 값 제거 후 Authentication 적용

:sparkles: [전주영] 로그인 유지session 값 제거, Authentication 활용

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/resources/templates/employee/approval/approval_edit.html
src/main/resources/templates/employee/approval/approval_progress_detail.html

:tada: [전주영] 전자결재 수정 html 경로 생성

---

src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js

**문서함**
- 개인 문서함 검색 기능 수정
- 부서 문서함 검색 기능 구현

🎉 [박혜선] 부서 문서함 검색 기능 구현

---

src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 생성시 생기는 오류 수정
- 목록과 관련된 생성 오류

:sparkles: [김채영] 채팅방 생성시 생기는 오류 수정

---

src/main/resources/static/css/employee/document/company.css
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js

**문서함**
- 개인 문서함, 부서 문서함 js 수정
- 사내 문서함 검색 기능 구현
- 사내 문서함 css 수정

🎉 [박혜선] 사내 문서함 검색 기능 구현

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMemberController.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatMemberService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 그룹 채팅방에서 초대 할 때 실시간 전송 오류 수정

:sparkles: [김채영] 그룹 채팅방 초대 오류 수정

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalApiController.java
src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalFileRepository.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalFlowRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalFileService.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/static/css/employee/approval/approval_edit.css
src/main/resources/static/js/employee/approval/approval_edit.js
src/main/resources/static/js/employee/approval/approval_progress_detail.js
src/main/resources/static/js/employee/approval/approval_progress_edit.js
src/main/resources/templates/employee/approval/approval_create.html
src/main/resources/templates/employee/approval/approval_edit.html

- 파일 있을 때 
- 파일 없을 때
- 결재자 수정시 두 번 들어가는 것 수정

:sparkles: [전주영] 전자결재 수정 기능 구현완료

---

src/main/java/com/fiveLink/linkOffice/survey/controller/SurveyViewController.java
src/main/java/com/fiveLink/linkOffice/survey/domain/Survey.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyOption.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyParticipant.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyQuestion.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyQuestionDto.java
src/main/java/com/fiveLink/linkOffice/survey/repository/SurveyOptionRepository.java
src/main/java/com/fiveLink/linkOffice/survey/repository/SurveyQuestionRepository.java
src/main/java/com/fiveLink/linkOffice/survey/repository/SurveyRepository.java
src/main/java/com/fiveLink/linkOffice/survey/repository/SurveyTextRepository.java
src/main/java/com/fiveLink/linkOffice/survey/service/SurveyService.java
src/main/resources/templates/employee/survey/survey_ing_list.html
src/main/resources/templates/employee/survey/survey_question_detail.html

✨ [김민재] 설문 진행중 세부 문항 출력

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMemberController.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatMemberService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js

- 메시지 권한 설정 오류로 인한 채팅 생성 오류 발생
- 채팅 생성에는 무리가 없으나 실시간 반영에 오류 
- 소켓에서 값을 받을 때 타입 별로 조건을 구성하여 해결

:sparkles: [김채영] 개인 채팅방 생성 시 실시간 반영 수정

---

src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/resources/static/js/employee/member/myedit.js

:sparkles: [전주영] 내 정보 수정 취소 버튼 경로 수정

---

src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/static/js/admin/chat/chatMessage.js

- 그룹 채팅방 생성 오류 
- 게인 채팅방 처럼 실시간 생성 수정

:sparkles: [김채영] 그룹 채팅 생성 시 실시간 반영 오류 수정

---

src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApproval.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalDto.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalFlow.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalFlowDto.java
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html

:sparkles: [전주영] 휴가 신청함 상세 조회 결재 css 수정

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/java/com/fiveLink/linkOffice/schedule/domain/ScheduleRepeatDto.java
src/main/java/com/fiveLink/linkOffice/schedule/repository/ScheduleRepeatRepository.java
src/main/java/com/fiveLink/linkOffice/schedule/repository/ScheduleRepository.java
src/main/java/com/fiveLink/linkOffice/schedule/service/ScheduleService.java
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/templates/admin/schedule/companySchedule.html

**관리자 사내 일정**
- 반복 일정 등록
- 반복 종료일 필수 지정으로 변경
- 반복 일정, 기본 일정 fullcalendar 출력 성공............ ㅠ뿌앵

:sparkles: [서혜원] 관리자 등록된 사내 일정 달력 출력

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentFileController.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFileService.java
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css
src/main/resources/static/js/employee/attendance/myAttendance.js
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js

**문서함**
- 각 문서함 파일 다운 기능 구현
- 문서함 js, css 수정
- myAttendance.js 92번째 줄 주석 삭제

🎉  [박혜선] 문서함 파일 다운 기능 구현

---

src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyOptionDto.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyQuestionDto.java
src/main/java/com/fiveLink/linkOffice/survey/repository/SurveyQuestionRepository.java
src/main/java/com/fiveLink/linkOffice/survey/service/SurveyService.java
src/main/resources/static/css/employee/survey/survey_question_detail.css
src/main/resources/templates/employee/survey/survey_question_detail.html

1. 선택형 리스트 출력
2. css 수정
3. 선택 답 count box 추가

✨ [김민재] 설문 진행중 선택형 리스트 출력

---

src/main/resources/static/js/employee/approval/approval.js
src/main/resources/static/js/employee/vacationapproval/approval.js
src/main/resources/templates/employee/approval/approval_create.html
src/main/resources/templates/employee/approval/approval_edit.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_create.html

✨ [전주영] 휴가결재, 결재 등록 js 수정 (이름과 직위 나누기)

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentFileController.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFileService.java
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js

**문서함**
- 각 문서함 파일 선택 다운 기능 구현
- 각 문서함 파일 미리보기 기능 구현
- 각 문서함 js, css 수정
- documentFileController, documentFileService 미리보기 코드 추가

🎉 [박혜선] 문서함 파일 미리보기 기능 구현

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/admin/schedule/companySchedule.css
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/templates/admin/schedule/companySchedule.html

**관리자 일정**
- 상세 모달
- 달력 공휴일
- 달력 일정 출력 순서 수정

:sparkles: [서혜원] 관리자 사내 일정 달력 css 수정

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatRoomController.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatMember.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatMemberDto.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 채팅 생성시 그룹 이름 작성 후 input리셋
- 채팅방 고정하기 구현

🎉 [김채영] 채팅방 고정하기 구현

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatRoomController.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatRoomService.java
src/main/resources/static/js/admin/chat/chatMessage.js

:tada: [김채영] 채팅방 고정해제 구현

---

src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html
src/main/resources/templates/include/layout.html

- 채팅방 아이콘 버전 업그레이드
- 채팅방 목록 출력 시 고정인 채팅방 표시

🎉 [김채영] 채팅방 목록 고정 출력

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatRoomController.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatRoomService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

:tada: [김채영] 채팅방 참여자 수 출력

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentApiController.java
src/main/java/com/fiveLink/linkOffice/document/controller/DocumentFileController.java
src/main/java/com/fiveLink/linkOffice/document/controller/DocumentViewController.java
src/main/java/com/fiveLink/linkOffice/document/domain/DocumentFileDto.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFileService.java
src/main/resources/static/css/employee/attendance/myAttendance.css
src/main/resources/static/css/employee/document/bin.css
src/main/resources/static/js/employee/document/bin.js
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/bin.html
src/main/resources/templates/employee/document/personal.html

**문서함**
- 휴지통 파일 목록 출력&검색 기능 구현
- 파일 목록 존재하지 않을 때 체크박스 비활성화
- documentFileDto 수정
- document/personal.html 수정
- documentViewController, documentApiController, documentService 휴지통 코드 추가
- document/bin.js 생성
- bin.css, bin.html 수정

🎉  [박혜선] 문서함 휴지통 파일 출력

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/java/com/fiveLink/linkOffice/schedule/repository/ScheduleRepeatRepository.java
src/main/java/com/fiveLink/linkOffice/schedule/service/ScheduleService.java
src/main/resources/application.properties
src/main/resources/static/css/admin/schedule/companySchedule.css
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/templates/admin/schedule/companySchedule.html

**관리자 일정**
- 일반 일정 구현
-> 일반 일정 수정
-> 반복 일정으로 수정

:sparkles: [서혜원] 관리자 일반 일정 -> 일반 수정, 반복 수정 구현

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalApiController.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/resources/static/css/employee/approval/approval_history_vacation_detail.css
src/main/resources/static/js/employee/approval/approval_history_vacation_detail.js
src/main/resources/templates/employee/approval/approval_history_detail.html
src/main/resources/templates/employee/approval/approval_history_vacation_detail.html

:sparkles: [전주영] 상세 조회 (전자결재) 승인, 승인 취소

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentFileController.java
src/main/java/com/fiveLink/linkOffice/document/repository/DocumentFileRepository.java
src/main/resources/static/css/employee/document/bin.css
src/main/resources/static/js/employee/document/bin.js

🎉  [박혜선] 문서함 휴지통 파일 복구 기능 구현

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalApiController.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/resources/static/css/employee/approval/approval_history_vacation_detail.css
src/main/resources/static/js/employee/approval/approval_history_detail.js
src/main/resources/static/js/employee/approval/approval_history_vacation_detail.js
src/main/resources/templates/employee/approval/approval_history_detail.html

:sparkles: [전주영] 상세 조회 (전자결재) 승인 취소 css 변경 및 반려 기능 구현 완료

---

build.gradle
src/main/java/com/fiveLink/linkOffice/CustomErrorController.java
src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalFileService.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalFileService.java
src/main/resources/static/css/employee/approval/approval_create.css
src/main/resources/static/css/employee/approval/approval_edit.css
src/main/resources/static/css/error.css
src/main/resources/static/js/employee/approval/approval_edit.js
src/main/resources/static/js/employee/approval/approval_history_list.js
src/main/resources/templates/employee/approval/approval_edit.html
src/main/resources/templates/employee/approval/approval_history_list.html
src/main/resources/templates/employee/approval/approval_history_vacation_detail.html
src/main/resources/templates/employee/approval/approval_progress_detail.html
src/main/resources/templates/employee/approval/approval_reject_detail.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html
src/main/resources/templates/error.html
src/main/resources/templates/home.html

- 결재선 값 가져오기
- td 6개 고정해야하는 부분 수정중
- home.html 
- 기안 취소 후 수정 버튼 X 
- 파일 다운로드 수정

:sparkles: [전주영] 수정 결재선 지정 수정중

---

src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js

:sparkles: [전주영] 휴가결재 양식 변경

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentFileController.java
src/main/resources/static/js/employee/document/bin.js

🎉 : [박혜선] 문서함 휴지통 선택 복구 기능 구현

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/resources/static/js/employee/approval/approval_edit.js
src/main/resources/static/js/employee/approval/approval_progress_edit.js
src/main/resources/templates/employee/approval/approval_edit.html

:sparkles: [전주영] 전자결재 수정 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/resources/static/css/employee/vacationapproval/vacationapproval_edit.css
src/main/resources/static/js/employee/vacationapproval/approval_edit.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_edit.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_edit.html

:sparkles: [전주영] 휴가결재 수정 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalApiController.java
src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/resources/static/js/employee/approval/approval.js
src/main/resources/static/js/employee/approval/approval_create.js
src/main/resources/static/js/employee/approval/approval_edit.js
src/main/resources/static/js/employee/approval/approval_progress_edit.js
src/main/resources/static/js/employee/vacationapproval/approval.js
src/main/resources/static/js/employee/vacationapproval/approval_edit.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_edit.js
src/main/resources/static/js/include/header.js
src/main/resources/static/js/pwchange.js

:sparkles: [전주영] 결재 주석 변경

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/java/com/fiveLink/linkOffice/schedule/service/ScheduleService.java

**관리자 사내 일정**
반복 일정 수정
-> 모든 일정으로 수정 구현

:sparkles: [서혜원] 반복 일정 수정 - 모든 일정 수정 구현

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMemberController.java
src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMessageController.java
src/main/java/com/fiveLink/linkOffice/chat/controller/ChatRoomController.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/java/com/fiveLink/linkOffice/webSocket/WebSocketHandler.java
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

✨ [김채영] 그룹 채팅 생성 그룹명 제한 수정

---

src/main/resources/static/css/employee/document/bin.css
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css

✨ : [박혜선] 문서함 css 수정

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentApiController.java
src/main/java/com/fiveLink/linkOffice/document/controller/DocumentFileController.java
src/main/resources/static/js/employee/document/bin.js
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/company.html
src/main/resources/templates/employee/document/department.html
src/main/resources/templates/employee/document/personal.html

**문서함**
- 문서함 폴더 삭제할 때 긴 swal 문구 개행 코드 추가
- 문서함 휴지통 복구할 때 긴 swal 문구 개행 코드 추가

✨ [박혜선] 문서함 swal 문자 개행

---

src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js

:sparkles: [김채영] 채팅 안읽음 개수 css 수정

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatRoomController.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatRoomService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js

:tada: [김채영] 채팅 중복 확인 기능

---

build.gradle
src/main/java/com/fiveLink/linkOffice/chat/service/ChatRoomService.java
src/main/resources/application.properties
src/main/resources/static/js/admin/chat/chatMessage.js

✨ [김채영] 채팅 중복 확인 모달 창

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/resources/templates/employee/approval/approval_references_list.html

:sparkles: [전주영] 전자결재 참조함 검색 및 정렬

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/java/com/fiveLink/linkOffice/schedule/service/ScheduleService.java
src/main/resources/application.properties
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/static/js/admin/schedule/companySchedule.js

**관리자 일정**
- 이 일정 및 향후 일정 수정 구현

:sparkles: [서혜원] 관리자 일정 이 일정 및 향후 일정 수정 구현

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/resources/templates/admin/approval/approval_form.html
src/main/resources/templates/employee/approval/approval_references_list.html

:sparkles: [전주영] 전자결재 참조함 정렬 및 페이징 / 결재 정렬 수정

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/repository/ApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js
src/main/resources/templates/employee/approval/approval_history_list.html
src/main/resources/templates/employee/approval/approval_progress_list.html
src/main/resources/templates/employee/approval/approval_references_list.html
src/main/resources/templates/employee/approval/approval_reject_list.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_list.html

- 정렬 및 검색
- 페이징
- 페이징 부분 type 추가

:sparkles: [전주영] 전자결재 내역함 정렬 및 검색 / 페이징 구현완료 및 페이징 검색 type 수정

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/java/com/fiveLink/linkOffice/schedule/domain/ScheduleException.java
src/main/java/com/fiveLink/linkOffice/schedule/domain/ScheduleExceptionDto.java
src/main/java/com/fiveLink/linkOffice/schedule/repository/ScheduleExceptionRepository.java
src/main/java/com/fiveLink/linkOffice/schedule/service/ScheduleService.java
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/templates/admin/schedule/companySchedule.html

**관리자 일정**
- 이 일정 / 이 일정 및 향후 일정 / 모든 일정 수정 구현 완료
- 뿌앵

:sparkles: [서혜원] 관리자 일정 수정 기능 구현 완료

---

src/main/resources/static/js/admin/chat/chatMessage.js

- 메시지 전송 시, enter가능하고 enter+shift는 줄바꿈 처리
- 메시지 입력 후 다른 채팅방 이동 시, 내용 리셋

:sparkles: [김채영] 채팅 메시지 Enter 보냄 & 채팅방 이동시 input내용 분리

---

src/main/resources/static/js/admin/chat/chatMessage.js

- 채팅방(개인, 그룹) 생성 시, 고정 아래 실시간 생성하기

:sparkles: [김채영] 채팅방 생성시 고정아래 생성

---

src/main/java/com/fiveLink/linkOffice/chat/service/ChatRoomService.java
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 지정 세로 길이를 목록과 메시지 부분이 넘어갈 경우 스크롤 생성

:tada: [김채영] 채팅방 목록과 채팅메시지 스크롤 생성

---

src/main/resources/static/css/employee/document/bin.css
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css

**문서함**
- 각 문서함 css 수정
- company.html 수정

✨ [박혜선] 문서함 css 수정

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/java/com/fiveLink/linkOffice/schedule/service/ScheduleService.java
src/main/resources/application.properties
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/static/js/admin/schedule/scheduleCategory.js
src/main/resources/templates/admin/schedule/companySchedule.html

**관리자 일정**
- 일정 등록
- 수정
- 삭제 구현 완료

:sparkles: [서혜원] 반복 일정 삭제 구현 완료

---

src/main/resources/mappers/chatMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js

- 실시간 목록 업데이트 완료
- 고정을 제외한 다른 목록은 메시지 전송과 동시에 가능

🎉 [김채영] 채팅 실시간 메시지 전송 시, 목록 실시간 변경

---

.gitignore
build.gradle
src/main/resources/application.properties
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js

:sparkles: [전주영] 휴가결재 공휴일 API 사용 일수 제외

---

src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/css/include/header.css
src/main/resources/static/css/include/nav.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/static/js/include/header.js
src/main/resources/static/js/include/nav.js
src/main/resources/templates/admin/chat/chatMessage.html
src/main/resources/templates/include/header.html
src/main/resources/templates/include/layout.html
src/main/resources/templates/include/nav.html

:sparkles: [김채영] 헤더, 사이드바 css 수정

---

src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/include/nav.js

**부서 문서함 알림**
- 해당 부서에 속한 사원들 조회를 위한 private final MemberRepository memberRepository 코드 추가
- NoficationWebSocketHandler에 부서 문서함 알림 코드 추가
- employee/department.js에 NoficationWebSocketHandler로 값을 보내는 코드 추가
- nav.js에 부서 문서함 알림 코드 추가

🎉 [박혜선] 부서 문서함 알림 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/java/com/fiveLink/linkOffice/schedule/service/ScheduleService.java
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/templates/admin/schedule/companySchedule.html
src/main/resources/templates/employee/schedule/employeeSchedule.html

:sparkles: [서혜원] 사원 일정 수정 구현 완료

---

src/main/resources/static/css/include/nav.css
src/main/resources/static/js/include/nav.js
src/main/resources/templates/include/nav.html

:sparkles: [김채영] 사이드바 수정

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/templates/employee/schedule/employeeSchedule.html

:sparkles: [서혜원] 사원 일정 삭제 구현 완료

---

src/main/resources/static/css/include/nav.css
src/main/resources/static/js/include/nav.js
src/main/resources/templates/include/nav.html

✨ [김채영] 사이드바 수정

---

src/main/java/com/fiveLink/linkOffice/attendance/controller/AttendanceApiController.java
src/main/resources/static/css/employee/attendance/attendance.css
src/main/resources/static/js/employee/attendance/attendance.js
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/weather/weather.js
src/main/resources/templates/employee/document/company.html
src/main/resources/templates/employee/document/department.html

**출퇴근**
- AttendanceApiController 수정
- attendance.js 수정
- attendance.css 수정
**문서함**
- 전체 검색 기능 추가
- 사원명+직위명 출력 시 띄워쓰기 추가

✨  [박혜선] 미출근 시 퇴근 버튼 비활성화

---

build.gradle
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/application.properties
src/main/resources/static/js/employee/approval/approval_create.js
src/main/resources/static/js/employee/approval/approval_history_detail.js
src/main/resources/static/js/employee/approval/approval_history_vacation_detail.js
src/main/resources/static/js/employee/approval/approval_progress_edit.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_edit.js
src/main/resources/static/js/include/nav.js

*** 전자결재
- 알림 수정 완료
- 결재자 미지정 시 alert ( 등록, 수정 )
*** 휴가결재 
- 이전 기간 disable
- 결재자 미지정 시 alert ( 등록, 수정 )

✨ [전주영] 전자결재 알림 수정 완료

---

src/main/resources/static/js/employee/approval/approval.js
src/main/resources/static/js/employee/approval/approval_edit.js
src/main/resources/static/js/employee/vacationapproval/approval.js
src/main/resources/static/js/employee/vacationapproval/approval_edit.js

- 전자결재
- 등록 시 결재선 지정 결재자 6명 이상 선택 alert 
- 수정 시 결재선 지정 결재자 6명 이상 선택 alert
- 휴가결재
- 등록 시 결재선 지정 결재자 6명 이상 선택 alert
- 수정 시 결재선 지정 결재자 6명 이상 선택 alert

:sparkles: [전주영] 결재선 지정시 결재자 6명 alert

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/resources/templates/employee/approval/approval_history_list.html
src/main/resources/templates/employee/approval/approval_references_list.html

:sparkles: [전주영] 결재 수신함 목록 기안자 직위명 출력

---

src/main/java/com/fiveLink/linkOffice/mapper/NoficationMapper.java
src/main/java/com/fiveLink/linkOffice/nofication/controller/NoficationController.java
src/main/java/com/fiveLink/linkOffice/nofication/service/NoficationService.java
src/main/resources/mappers/noficationMapper.xml
src/main/resources/static/css/include/header.css
src/main/resources/static/js/include/header.js
src/main/resources/templates/include/header.html

:tada: [김채영] 통합알림 개수 구현

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/domain/VacationApprovalDto.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/service/VacationApprovalService.java
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/templates/employee/schedule/employeeSchedule.html

**사원 일정**
- 달력 휴가 출력
1. vactionapprovalDto 
- position_name / department_name / department_no 추가 
2. vactionapprovalRepository 코드 추가
3. vacationapprovalService 코드 추가

:sparkles: [서혜원] 사원 일정 휴가 출력

---

src/main/java/com/fiveLink/linkOffice/mapper/NoficationMapper.java
src/main/java/com/fiveLink/linkOffice/nofication/controller/NoficationController.java
src/main/java/com/fiveLink/linkOffice/nofication/service/NoficationService.java
src/main/resources/mappers/noficationMapper.xml
src/main/resources/static/js/include/header.js
src/main/resources/templates/include/header.html

- 통합알림 모달 일괄읽음 처리
- 모든 알림 한번에 읽음 처리

:tada: [김채영] 통합알림 일괄읽음 처리

---

src/main/resources/static/js/include/header.js
src/main/resources/static/js/include/nav.js

:tada: [김채영] 통합알림 실시간 개수 증가

---

src/main/java/com/fiveLink/linkOffice/mapper/NoficationMapper.java
src/main/java/com/fiveLink/linkOffice/nofication/controller/NoficationController.java
src/main/java/com/fiveLink/linkOffice/nofication/service/NoficationService.java
src/main/resources/mappers/noficationMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/static/js/include/header.js

- 기능 별 페이지 이동 시 안읽음 읽음 처리후 개수 변화

:tada: [김채영] 기능별 실시간 개수 증가 제한

---

src/main/resources/static/css/home.css
src/main/resources/templates/home.html

:sparkles: [전주영] 메인 내정보 css 수정

---

src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/mappers/noficationMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/static/js/include/header.js
src/main/resources/static/js/include/nav.js

- 보낸 실시간 알림과 현재 본인이 있는 페이지가 같을 경우, 알림 개수와 모달 제한

:sparkles: [김채영] 기능별 실시간 개수 증가 제한

---

src/main/resources/static/css/employee/document/bin.css
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/bin.html
src/main/resources/templates/employee/document/company.html
src/main/resources/templates/employee/document/department.html
src/main/resources/templates/employee/document/personal.html

**문서함**
- 문서함 모달 크기 수정&어떤 모달창인지 명시
- 문서함 버튼 아이콘으로 수정

✨ [박혜선] 문서함 모달&버튼 수정

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/java/com/fiveLink/linkOffice/schedule/domain/ScheduleDto.java
src/main/java/com/fiveLink/linkOffice/schedule/domain/ScheduleExceptionDto.java
src/main/java/com/fiveLink/linkOffice/schedule/repository/ScheduleExceptionParticipantRepository.java
src/main/java/com/fiveLink/linkOffice/schedule/repository/ScheduleParticipantRepository.java
src/main/java/com/fiveLink/linkOffice/schedule/service/ScheduleService.java
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/templates/employee/schedule/employeeSchedule.html

:sparkles: [서혜원] 일정 참여자 목록 출력

---

src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/static/css/include/nav.css
src/main/resources/static/js/include/header.js
src/main/resources/static/js/include/nav.js

:sparkles: [김채영] 실시간 알림 모달 시간 추가

---

src/main/java/com/fiveLink/linkOffice/member/controller/MemberApiController.java
src/main/java/com/fiveLink/linkOffice/member/controller/MemberViewController.java
src/main/java/com/fiveLink/linkOffice/util/AESUtil.java
src/main/resources/static/js/include/nav.js
src/main/resources/templates/admin/member/create.html

** 사원 관리
- 사원 등록 주민번호 암호화
- 사원 조회 암호화
** 비밀번호 변경
- 주민번호 복호화하여 비교
** 사원 정보
- 내정보, 정보 수정 복호화하여 출력

:tada: [전주영] 주민번호 양방향 암호화 기능 구현 완료

---

src/main/resources/static/js/employee/weather/weather.js

✨ [박혜선] 날씨 js 수정

---

src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingParticipantRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingReservationRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingReservationService.java
src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/resources/application.properties
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/templates/employee/schedule/employeeSchedule.html

:sparkles: [서혜원] 사원 회의실 일정 출력

---

build.gradle
src/main/java/com/fiveLink/linkOffice/mapper/NoficationMapper.java
src/main/java/com/fiveLink/linkOffice/nofication/controller/NoficationController.java
src/main/java/com/fiveLink/linkOffice/nofication/service/NoficationService.java
src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/application.properties
src/main/resources/mappers/noficationMapper.xml
src/main/resources/static/js/include/header.js
src/main/resources/static/js/include/nav.js
src/main/resources/templates/include/header.html

- 실시간 기능 모두 작용하게 구현
- 읽음 처리도 실시간 가능

:sparkles: [김채영] 실시간 읽음 처리와 리스트 업 수정

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/js/include/nav.js

:sparkles: [전주영] 결재 참조 알림 수정

---

src/main/resources/static/css/employee/attendance/myAttendance.css
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css

**근태 조회**
- 오늘 버튼 css 수정
- 페이징 버튼 css 수정
**문서함**
- 폴더 생성&삭제 버튼 css 수정

✨ [박혜선] 문서함 폴더 삭제&생성 버튼 css 수정

---

src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/templates/admin/schedule/companySchedule.html
src/main/resources/templates/employee/schedule/employeeSchedule.html

:sparkles: [서혜원] 일정 검색 기능 추가

---

build.gradle
src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingReservationController.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingReservationService.java
src/main/resources/application.properties
src/main/resources/static/css/admin/schedule/companySchedule.css
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/employee/schedule/employeeSchedule.css
src/main/resources/static/css/home.css
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/static/js/employee/meeting/homeMeeting.js
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/static/js/employee/schedule/homeSchedule.js
src/main/resources/templates/admin/schedule/companySchedule.html
src/main/resources/templates/employee/schedule/employeeSchedule.html
src/main/resources/templates/employee/vacationapproval/home.html
src/main/resources/templates/home.html
src/main/resources/templates/include/nav.html

**메인 회의실, 일정**
- 메인 페이지 회의실 예약 내역, 일정 출력
1. nav.html
- 관리자 일정 목록 삭제
2. home.html
- 상단 fullcalendar script 2줄 추가
3. home.css 수정
4. home.html 수정
- 일정, 회의실 부분
- homeSchedule.js & homeMeeting.js 연결
5. homeController 수정

✨ [서혜원] 메인 페이지 회의실, 일정 기능 추가

---

src/main/resources/static/css/employee/document/bin.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/js/employee/document/bin.js
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/bin.html

**문서함**
- js 파일에 폴더 생성, 이름 변경 후 해당 모달 hide하는 코드 추가
- 부서 문서함 버튼 css 수정
**문서함 휴지통**
- 파일 복구, 파일 영구 삭제 버튼 icon으로 변경
- 휴지통 용량 기능 없앰

✨ [박혜선] 문서함 휴지통 용량 제거

---

src/main/java/com/fiveLink/linkOffice/chat/domain/ChatRead.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js

✨ [김채영] 채팅 생성 관련 수정

---

src/main/resources/static/css/employee/document/bin.css

✨ [박혜선] 문서함 휴지통 버튼 css 수정

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalApiController.java
src/main/java/com/fiveLink/linkOffice/approval/service/ApprovalService.java
src/main/java/com/fiveLink/linkOffice/mapper/NoficationMapper.java
src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/mappers/noficationMapper.xml
src/main/resources/static/js/employee/approval/approval_create.js
src/main/resources/static/js/employee/approval/approval_history_detail.js
src/main/resources/static/js/employee/approval/approval_progress_list.js
src/main/resources/static/js/employee/approval/approval_reject_list.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js

- 결재 문서 승인 시 기안자 알림
- 결재 문서 반려 시 기안자 알림
- 결재 문서 등록 시 결재자 알림
- 결재 문서 등록 시 참조자 알림
- 결재 문서 승인 시 다음 결재자 알림
- 상세 페이지 진입 시 읽음 처리

:sparkles: [전주영] 전자결재 알림 및 읽음 처리 완료

---

src/main/java/com/fiveLink/linkOffice/mapper/NoficationMapper.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/repository/VacationApprovalRepository.java
src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/static/js/employee/approval/approval_create.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js

- 참조자 알림 문구 제목 추가 
- 결재자 알림 문구 제목 추가
- 참조자 알림 문구 제목 추가 
- 결재자 알림 문구 제목 추가

 [전주영] 결재 참조, 결재 알림 제목 추가 수정 완료

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/java/com/fiveLink/linkOffice/schedule/service/ScheduleService.java
src/main/resources/static/css/employee/meeting/reservationDetail.css

:sparkles: [서혜원] 페이지 css 수정

---

src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js

:sparkles: [전주영] 휴가결재 날짜 오늘이전 막기 수정

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/admin/meeting/meetingReservationList.css
src/main/resources/static/css/admin/meeting/meetingroomList.css
src/main/resources/static/css/admin/organization/departmentList.css
src/main/resources/static/css/admin/organization/positionList.css
src/main/resources/static/css/admin/permission/permission.css
src/main/resources/static/css/employee/meeting/myMeetingReservation.css
src/main/resources/static/css/home.css
src/main/resources/static/css/include/header.css
src/main/resources/static/css/include/layout.css
src/main/resources/static/js/admin/meeting/meetingReservationList.js
src/main/resources/static/js/admin/meeting/meetingroomList.js
src/main/resources/static/js/admin/organization/departmentList.js
src/main/resources/static/js/admin/organization/positionList.js
src/main/resources/static/js/admin/schedule/scheduleCategory.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/templates/admin/permission/permission.html
src/main/resources/templates/employee/meeting/meetingReservation.html
src/main/resources/templates/employee/meeting/myMeetingReservation.html
src/main/resources/templates/employee/meeting/reservationDetail.html
src/main/resources/templates/employee/schedule/employeeSchedule.html
src/main/resources/templates/include/header.html
src/main/resources/templates/include/layout.html
src/main/resources/templates/include/nav.html

✨ [서혜원] 페이지 디자인 수정

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatMessageController.java
src/main/java/com/fiveLink/linkOffice/chat/controller/ChatRoomController.java
src/main/java/com/fiveLink/linkOffice/chat/domain/ChatMemberDto.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatMessageService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/mappers/noficationMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

- 그룹 채팅에서 나간 후, 재 초대 가능
- 내용은 재초대된 부분부터 보이게 구현
- 개인 그룹 둘다 나간 상황이면 다시 생성가능

✨ [김채영] 채팅 그룹 재초대 & 나가기 후 재 생성할때 조건 수정

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentApiController.java
src/main/java/com/fiveLink/linkOffice/document/controller/DocumentFileController.java
src/main/java/com/fiveLink/linkOffice/document/service/DocumentFileService.java
src/main/resources/static/css/employee/document/bin.css
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css
src/main/resources/static/js/employee/document/bin.js
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/bin.html
src/main/resources/templates/employee/document/company.html
src/main/resources/templates/employee/document/department.html
src/main/resources/templates/employee/document/personal.html

**문서함 페이지**
- 현재 페이지 경로 h1 수정
**문서함 모달** 
- 첫 폴더 생성 모달 창 이름 ‘첫 폴더 생성’ → 폴더 생성
- 업로드 가능한 파일 형식 모달에 명시
- swal 텍스트 수정
**문서함 검색**
- 기간 검색 부분 ‘기간’ 텍스트 삭제
- 개인 문서함&휴지통 검색창 앞에 ‘파일명’ 텍스트 삭제
**문서함 버튼**
- 선택 다운, 선택 삭제, 선택 복구 버튼 체크박스 미선택 시 비활성화
**문서함 휴지통**
- 휴지통에서 문서 상위 폴더 복구 시 미리보기 가능

✨ [박혜선] 문서함 파일 복구 시 미리보기 가능

---

src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

:sparkles: [김채영] 채팅 나가기 실시간 인원수 보여주기

---

src/main/resources/static/js/employee/attendance/myAttendance.js

**근태 조회**
- 종료일을 시작일 이전 날짜로 선택하면 시작일 날짜가 자동으로 종료일 날짜값으로 변경 
- 종료일을 시작일 기본 설정 날짜 이전으로 선택해서 시작일이 기본 설정 날짜 이전으로 설정될 시 → 시작일을 삭제 → 변화없음
ex) 시작일 기본 설정 날짜 : 2024-09-01 → 종료일을 2024-08-30 로 설정 → 시작일이 자동으로 2024-08-30 로 설정 됨 → 시작일을 삭제 → 2024-08-30으로 변화없음

✨ [박혜선] 근태 조회 기간 선택 수정

---

src/main/resources/static/css/employee/attendance/attendance.css
src/main/resources/templates/home.html

✨ [박혜선] home에 근태조회 버튼 삭제

---

src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/static/css/include/layout.css
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/static/js/employee/meeting/reservationDetail.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/static/js/include/nav.js

**알림 추가**
1. 일정
- 부서 일정 등록 -> 해당 부서 멤버에게 알림
- 참여자 일정 등록 -> 선택 멤버에게 알림
2. 회의실 
- 참여자 멤버에게 알림
3. 일정 페이지 진입시 알림 목록 제거

:sparkles: [서혜원] 일정, 회의실 알림 추가

---

build.gradle
src/main/java/com/fiveLink/linkOffice/chat/service/ChatMessageService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/application.properties
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/css/include/header.css
src/main/resources/static/css/include/nav.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/static/js/include/nav.js

- 채팅 정렬 순서 수정
- 채팅 알림 문구 수정
- 모달창 가로 길이 증가

✨ [김채영] 알림 관련 수정

---

src/main/resources/application.properties
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js

:sparkles: [서혜원] 일정 기간 검색 오류 수정

---

src/main/resources/application.properties
src/main/resources/static/css/admin/schedule/companySchedule.css
src/main/resources/static/css/employee/schedule/employeeSchedule.css
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/templates/home.html

**일정**
- 일 선택 추가
- all-day -> 종일
**home.html**
- 주소록 삭제
- 근태조회 위치 변경

:sparkles: [서혜원] 일정 일 선택 추가

---

src/main/resources/static/css/employee/attendance/myAttendance.css
src/main/resources/static/js/employee/attendance/myAttendance.js
src/main/resources/templates/employee/attendance/myAttendance.html

**근태 조회**
- 달력 css 수정
- 근태 조회 리스트 css 수정
- 경로 h1 수정

✨ [박혜선] 근태 조회 css 수정

---

src/main/resources/static/css/include/header.css
src/main/resources/static/css/include/nav.css
src/main/resources/templates/include/header.html

- 알림 div 가로 길이 수정
- 헤더에 사원 이름 출력

:sparkles: [김채영] 알림 관련 수정 & header 사원 이름 출력

---

src/main/resources/static/js/include/nav.js

- 알림 js로 인해 비품 등록 모달이 안뜨는 현상 발생
- 모달 명을 다르게 선언

:sparkles: [김채영] 비품 관련 모달 중복 알림 수정

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/java/com/fiveLink/linkOffice/organization/controller/DepartmentController.java
src/main/java/com/fiveLink/linkOffice/organization/controller/PositionController.java
src/main/java/com/fiveLink/linkOffice/organization/domain/DepartmentDto.java
src/main/java/com/fiveLink/linkOffice/organization/repository/DepartmentRepository.java
src/main/java/com/fiveLink/linkOffice/organization/repository/PositionRepository.java
src/main/java/com/fiveLink/linkOffice/organization/service/DepartmentService.java
src/main/java/com/fiveLink/linkOffice/organization/service/PositionService.java
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/css/admin/organization/departmentList.css
src/main/resources/static/css/admin/organization/organizationChart.css
src/main/resources/static/css/admin/organization/positionList.css
src/main/resources/static/js/admin/meeting/meetingroomList.js
src/main/resources/static/js/admin/organization/departmentList.js
src/main/resources/static/js/admin/organization/positionList.js
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/static/js/employee/meeting/reservationDetail.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/static/js/employee/schedule/homeSchedule.js
src/main/resources/templates/admin/organization/department_list.html
src/main/resources/templates/admin/organization/position_list.html

**직위**
- 직위 수정 기능 추가
**회의실**
- 예약 후 일정 출력 오류 수정
- 회의실 참여자 일정 출력 오류 수정
**부서 관리**
- 부서별 소속 사원 수 출력
- 상위 부서인 경우 하위 부서의 소속 사원 수 총합 출력
**조직도**
- 검색 결과 디자인 수정
- 채팅 사원 초대 조직도 디자인 수정

:sparkles: [서혜원] 직위 수정 기능 추가, 회의실 예약 오류 수정

---

src/main/resources/static/css/include/nav.css
src/main/resources/static/js/admin/vacation/addVacation.js
src/main/resources/static/js/admin/vacation/vacationStandard.js
src/main/resources/static/js/include/header.js
src/main/resources/static/js/include/nav.js
src/main/resources/templates/admin/vacation/addVacation.html
src/main/resources/templates/admin/vacation/vacation.html
src/main/resources/templates/include/nav.html

- 알림 모달 창 관련되어서 클릭하면 해당 페이지로 이동
- 페이지에 휴가 관리 경로 나타내기
- 사이드바 드롭 메뉴는 로컬에 저장시켜 유지가 가능하나 a링크는 이동과 동시에 리로드가 되어 로컬에 저장되지 않는 것 같아
추후 수정 예정

✨ [김채영] 알림 관련 경로 이동

---

src/main/resources/static/css/admin/permission/permission.css
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/employee/meeting/reservationDetail.css
src/main/resources/static/css/employee/schedule/employeeSchedule.css
src/main/resources/static/css/include/layout.css
src/main/resources/static/js/include/header.js
src/main/resources/static/js/include/nav.js

**알림**
- 모달 선택시 경로 이동 추가
**조직도 검색 css**
- 회의실, 일정, 통합 권한 조직도 검색 css 추가

:sparkles: [서혜원] 알림 경로 이동 추가

---

src/main/java/com/fiveLink/linkOffice/security/config/WebSecurityConfig.java
src/main/resources/application.properties
src/main/resources/static/js/include/nav.js
src/main/resources/templates/include/nav.html

✨ [김채영] 사이드 바 권한 설정

---

src/main/java/com/fiveLink/linkOffice/schedule/controller/ScheduleApiController.java
src/main/resources/static/css/admin/schedule/companySchedule.css
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/employee/schedule/employeeSchedule.css
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/templates/employee/schedule/employeeSchedule.html

**회의실**
- 예약 현황, 정보 테이블 스크롤 디자인 추가
- 주간, 일 보기 화면 영역 넘어가는 문제 css 수정

:sparkles: [서혜원] 회의실 예약 현황, 정보 스크롤 디자인 추가

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/employee/approval/approval.css
src/main/resources/static/css/employee/approval/approval_progress_detail.css
src/main/resources/static/css/employee/vacationapproval/approval.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/static/css/home.css
src/main/resources/static/js/employee/approval/approval.js
src/main/resources/static/js/employee/approval/approval_edit.js
src/main/resources/static/js/employee/vacationapproval/approval.js
src/main/resources/static/js/employee/vacationapproval/approval_edit.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_detail.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html
src/main/resources/templates/home.html

- td 수정 했으나 다시 되돌림
- 조직도 6명 alert 수정
- 조직도 검색 css 수정
-  home 휴가 신청 버튼 생성

[전주영] home 휴가 신청 버튼 생성

---

src/main/resources/application.properties
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css
src/main/resources/static/js/employee/document/bin.js
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js

**문서함**
- 폴더 생성 시 상위 폴더의 파일 목록이 로드되는 오류 수정
- '+ 폴더 생성' 플러스 기호 background-color 수정
- 부서 문서함 진입 시 알림 읽음 처리(알림 개수 감소)
- 문서함 css 수정

✨ [박혜선] 문서함 폴더 생성 시 파일 로드 오류 수정

---

src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/static/js/include/header.js
src/main/resources/static/js/include/nav.js

[전주영] 결재 통합 알림 모달 제외

---

src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/static/js/include/nav.js

:sparkles: [전주영] 모달 결재 완료(기안자) 알림 제외

---

src/main/resources/application.properties
src/main/resources/templates/include/header.html

:sparkles: [서혜원] 결재 양식 관리 권한 수정

---

src/main/resources/static/js/admin/meeting/meetingReservationList.js
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/static/js/admin/schedule/scheduleCategory.js
src/main/resources/static/js/employee/meeting/reservationDetail.js
src/main/resources/templates/include/nav.html

:sparkles: [서혜원] 페이지 경로 출력 수정

---

src/main/resources/static/js/admin/meeting/meetingroomList.js
src/main/resources/static/js/admin/permission/permissionList.js
src/main/resources/templates/admin/meeting/meetingroomList.html
src/main/resources/templates/admin/permission/permission.html

회의실 정보 목록, 통합 권한 목록 전체 선택 체크박스 추가

:sparkles: [서혜원] 회의실 정보 목록, 통합 권한 목록 전체 선택 체크박스 추가

---

src/main/java/com/fiveLink/linkOffice/survey/controller/SurveyApiController.java
src/main/java/com/fiveLink/linkOffice/survey/controller/SurveyViewController.java
src/main/java/com/fiveLink/linkOffice/survey/repository/SurveyRepository.java
src/main/java/com/fiveLink/linkOffice/survey/service/SurveyService.java
src/main/resources/templates/admin/notice/notice_list.html
src/main/resources/templates/employee/survey/survey_create.html
src/main/resources/templates/employee/survey/survey_end_list.html
src/main/resources/templates/employee/survey/survey_ing_list.html
src/main/resources/templates/employee/survey/survey_my_list.html
src/main/resources/templates/employee/survey/survey_question_detail.html
src/main/resources/templates/employee/survey/survey_question_myResult.html
src/main/resources/templates/employee/survey/survey_question_update.html
src/main/resources/templates/employee/survey/survey_update.html

✨ [김민재] 설문 페이징 수정, 공지 작성 권한 설정

---

src/main/resources/static/css/employee/attendance/myAttendance.css

✨  [박혜선] 근태 조회 css 수정

---

src/main/java/com/fiveLink/linkOffice/mapper/VacationMapper.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationViewController.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationService.java
src/main/resources/mappers/vacationMapper.xml
src/main/resources/static/css/home.css
src/main/resources/static/js/employee/vacationapproval/homeVacationCount.js
src/main/resources/templates/home.html

- 휴가 지급 관련 메인 출력
- 휴가 개수 지급과 지급 기준 
- 사용 후 남은 개수 출력__

:sparkles: [김채영] 휴가 개수 지급 기준과 지급 개수, 남은 개수 출력

---

src/main/resources/static/css/employee/schedule/employeeSchedule.css
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js

:sparkles: [서혜원] 일정 상세 모달 위치 조정

---

src/main/java/com/fiveLink/linkOffice/document/service/DocumentFileService.java
src/main/resources/static/js/employee/document/bin.js
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js

**문서함**
- 문서함 파일 경로 수정 -> 불필요한 "\\" 삭제
- 검색 keyup 기능 추가

✨  [박혜선] 문서함 파일 경로 수정

---

src/main/java/com/fiveLink/linkOffice/nofication/service/NoficationService.java
src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/static/css/employee/approval/approval_history_vacation_detail.css
src/main/resources/static/css/employee/approval/approval_progress_detail.css
src/main/resources/static/css/employee/approval/approval_references_detail.css
src/main/resources/static/css/employee/approval/approval_reject_detail.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/static/js/employee/approval/approval_progress_detail.js
src/main/resources/static/js/include/nav.js
src/main/resources/templates/employee/approval/approval_progress_detail.html

- 통합 알림 모달 / 헤더 창 클릭 시 상세 이동
- 해당 url 이동 하여 js 에서 타입 2개인 경우 처리 갯수 감소 수정중

✨ [전주영] 결재 통합 알림 기능 구현 완료

---

src/main/java/com/fiveLink/linkOffice/notice/domain/NoticeDto.java
src/main/java/com/fiveLink/linkOffice/notice/repository/NoticeRepository.java
src/main/java/com/fiveLink/linkOffice/notice/service/NoticeService.java
src/main/java/com/fiveLink/linkOffice/survey/service/SurveyService.java
src/main/resources/templates/admin/inventory/inventory_create.html
src/main/resources/templates/admin/inventory/inventory_list.html
src/main/resources/templates/admin/notice/notice_create.html
src/main/resources/templates/admin/notice/notice_detail.html
src/main/resources/templates/admin/notice/notice_list.html
src/main/resources/templates/admin/notice/notice_update.html
src/main/resources/templates/employee/survey/survey_create.html
src/main/resources/templates/employee/survey/survey_end_list.html
src/main/resources/templates/employee/survey/survey_ing_list.html
src/main/resources/templates/employee/survey/survey_my_list.html
src/main/resources/templates/employee/survey/survey_question_detail.html
src/main/resources/templates/employee/survey/survey_question_myResult.html
src/main/resources/templates/employee/survey/survey_question_result.html
src/main/resources/templates/employee/survey/survey_update.html

✨ [김민재] 공지사항 리스트 수정, h1 수정

---

src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/application.properties
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/include/header.html

✨ [김채영] 총관리자 권한

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css

🎉[전주영] 총 관리자 로그인 시 경로 수정

---

src/main/resources/static/js/include/header.js
src/main/resources/templates/include/header.html

:sparkles: [김채영] 총 관리자 헤더 권한 설정

---

src/main/java/com/fiveLink/linkOffice/SpringWebConfig.java
src/main/resources/static/js/employee/document/department.js

SpringWebConfig 날씨 오류 관련 코드 추가

✨  [박혜선] SpringWebConfig 날씨 오류 관련 코드 추가

---

src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingReservationRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingReservationService.java
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/home.css
src/main/resources/static/js/employee/meeting/homeMeeting.js
src/main/resources/templates/home.html

:sparkles [서혜원] 메인 페이지 디자인 수정

---

src/main/resources/mappers/chatMapper.xml
src/main/resources/templates/admin/vacation/addVacation.html
src/main/resources/templates/include/header.html

:sparkles: [김채영] 채팅 안읽음 개수 수정

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/admin/approval/approval_form.css
src/main/resources/static/css/admin/member/list.css
src/main/resources/static/css/employee/approval/approval_history_list.css
src/main/resources/static/css/employee/approval/approval_history_vacation_detail.css
src/main/resources/static/css/employee/approval/approval_progress_list.css
src/main/resources/static/css/employee/approval/approval_references_list.css
src/main/resources/static/css/employee/approval/approval_reject_list.css
src/main/resources/static/css/employee/member/list.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_list.css
src/main/resources/templates/employee/approval/approval_history_vacation_detail.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html

- 휴가 신청함
- 전자결재 상신함
- 전자결재 수신함
- 주소록 
- 사원 목록 
- 전자결재 양식함

✨[전주영] 사용자측 목록 css 수정

---

src/main/java/com/fiveLink/linkOffice/survey/controller/SurveyApiController.java
src/main/java/com/fiveLink/linkOffice/survey/controller/SurveyViewController.java
src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyTextDto.java
src/main/java/com/fiveLink/linkOffice/survey/repository/SurveyTextRepository.java
src/main/java/com/fiveLink/linkOffice/survey/service/SurveyService.java
src/main/resources/static/css/employee/survey/survey_question_myResult.css
src/main/resources/static/css/employee/survey/survey_question_result.css
src/main/resources/templates/admin/notice/notice_list.html
src/main/resources/templates/employee/survey/survey_create.html
src/main/resources/templates/employee/survey/survey_end_list.html
src/main/resources/templates/employee/survey/survey_ing_list.html
src/main/resources/templates/employee/survey/survey_my_list.html
src/main/resources/templates/employee/survey/survey_question_detail.html
src/main/resources/templates/employee/survey/survey_question_myResult.html
src/main/resources/templates/employee/survey/survey_question_result.html

1. 답이 없을 경우 공백 없애기
2. 전체 참여자 참여완료 미참여 css 옆으로 옮기기
3. 박스에다가 링크 걸어주기
4. 공지사항 작성자 재수정
5. 텍스트 input 이상하게 들어가는거 수정

✨ [김민재] css 수정, 박스 링크, 텍스트 input 수정

---

src/main/java/com/fiveLink/linkOffice/document/controller/DocumentViewController.java
src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/include/header.js
src/main/resources/static/js/include/nav.js
src/main/resources/templates/include/header.html
src/main/resources/templates/include/nav.html

**부서 문서함 알림**
- 부서 번호 header.html에 input type="hidden"으로 선언해줌
- header.js에 부서 문서함 알림 경로 설정
- nav.js 부서 문서함 알림 모달 클릭 시 이동하게 수정
- NoficationWebSocketHandler 부서 알림 코드 수정
**문서함 경로**
- nav.html 문서함 경로 변경
- DocumentViewController 각 문서함 이동 코드 수정

✨ [박혜선] 부서 문서함 알림 모달 경로 설정

---

src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/employee/meeting/reservationDetail.css
src/main/resources/static/css/home.css
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/static/js/employee/schedule/homeSchedule.js
src/main/resources/templates/admin/meeting/meetingroomList.html
src/main/resources/templates/employee/schedule/employeeSchedule.html
src/main/resources/templates/home.html

:sparkles: [서혜원] 메인 일정 선택시 상세 모달 출력

---

src/main/java/com/fiveLink/linkOffice/survey/domain/SurveyDto.java
src/main/java/com/fiveLink/linkOffice/survey/service/SurveyService.java
src/main/resources/static/css/employee/survey/survey_question_detail.css
src/main/resources/templates/employee/survey/survey_end_list.html
src/main/resources/templates/employee/survey/survey_ing_list.html
src/main/resources/templates/employee/survey/survey_question_detail.html
src/main/resources/templates/employee/survey/survey_question_myResult.html
src/main/resources/templates/employee/survey/survey_question_result.html

✨ [김민재] 설문 이름+ 직책 추가

---

src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/js/admin/chat/chatMessage.js

:tada: [김채영] 채팅 실시간 초대 문구 추가

---

src/main/java/com/fiveLink/linkOffice/chat/service/ChatRoomService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js

:tada: [김채영] 채팅 실시간 나가기 문구 출력

---

src/main/resources/application.properties
src/main/resources/static/js/admin/chat/chatMessage.js

- 채팅방 생성시, 랜덤 위치 조정되어 실시간 생성 반영이 안되는 오류 발생
- 수정완료

✨ [김채영] 채팅 생성시, 랜덤 위치 오류 수정

---

src/main/resources/static/css/admin/schedule/companySchedule.css
src/main/resources/static/css/admin/schedule/scheduleCategory.css
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/employee/meeting/reservationDetail.css
src/main/resources/static/css/employee/schedule/employeeSchedule.css
src/main/resources/static/css/home.css
src/main/resources/static/js/employee/meeting/meetingReservation.js

:sparkles: [서혜원] 달력, 사원 회의실css 수정

---

src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/company.html
src/main/resources/templates/employee/document/department.html
src/main/resources/templates/employee/document/personal.html

**문서함**
- 생성된 폴더가 없을 시 폴더 목록 띄우는 div 안 보이게 수정

✨  [박혜선] 문서함 폴더 css 수정

---

src/main/resources/static/css/employee/attendance/myAttendance.css
src/main/resources/static/css/employee/document/bin.css
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css

**근태 조회**
- 페이징 버튼 hover 시 텍스트 색상 검정색 유지
**문서함**
- 페이징 버튼 hover 시 텍스트 색상 검정색 유지

✨  [박혜선] 근태 조회&문서함 페이징 css 수정

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/admin/meeting/meetingReservationList.css
src/main/resources/static/css/admin/meeting/meetingroomList.css
src/main/resources/static/css/admin/organization/departmentList.css
src/main/resources/static/css/admin/organization/organizationChart.css
src/main/resources/static/css/admin/organization/positionList.css
src/main/resources/static/css/admin/permission/permission.css
src/main/resources/static/css/admin/schedule/companySchedule.css
src/main/resources/static/css/admin/schedule/scheduleCategory.css
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/employee/meeting/myMeetingReservation.css
src/main/resources/static/css/employee/meeting/reservationDetail.css
src/main/resources/static/css/employee/schedule/employeeSchedule.css
src/main/resources/static/css/include/layout.css
src/main/resources/static/js/admin/meeting/meetingroomList.js
src/main/resources/static/js/admin/organization/departmentList.js
src/main/resources/static/js/admin/organization/positionList.js
src/main/resources/static/js/admin/permission/permissionList.js
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/static/js/admin/schedule/scheduleCategory.js
src/main/resources/static/js/employee/meeting/meetingReservation.js
src/main/resources/static/js/employee/meeting/reservationDetail.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js

버튼, swal css 수정
- 일정
- 회의실
- 부서
- 직위
- 통합 권한
**공통 swal**
- text 색상 변경

:sparkles: [서혜원] 버튼, swal css 수정

---

src/main/resources/static/css/admin/vacation/addVacation.css
src/main/resources/templates/admin/vacation/addVacation.html

:sparkles: [김채영] 휴가 종류 목록 스크롤바

---

src/main/java/com/fiveLink/linkOffice/webSocket/NoficationWebSocketHandler.java
src/main/resources/static/css/admin/vacation/addVacation.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/vacation/addVacation.html
src/main/resources/templates/include/header.html

- 채팅 그룹 알림 두개 수정
- 채팅 나간 사용자에게 알림 허용되지 않게
- 휴가 생성 css 수정

✨ [김채영] 채팅 오류 수정

---

src/main/resources/static/css/employee/approval/approval_create.css
src/main/resources/static/js/admin/member/list.js

:sparkles:[전주영] 전자결재 등록 css 수정

---

src/main/resources/static/css/admin/organization/departmentList.css
src/main/resources/static/css/home.css
src/main/resources/static/css/include/layout.css
src/main/resources/static/js/employee/schedule/homeSchedule.js
src/main/resources/templates/admin/inventory/inventory_create.html
src/main/resources/templates/home.html
src/main/resources/templates/include/nav.html

메인 디자인 수정, 비품 등록 swal, 비품 nav 순서 수정

:sparkles: [서혜원] 메인 디자인 수정, 비품 등록 swal, 비품 nav 순서 수정

---

build.gradle
src/main/java/com/fiveLink/linkOffice/vacation/service/AddVacationSchedulerService.java
src/main/resources/application.properties
src/main/resources/static/js/admin/chat/chatMessage.js

✨ [김채영] 스케쥴링 오류 잡기

---

src/main/java/com/fiveLink/linkOffice/member/domain/Member.java
src/main/java/com/fiveLink/linkOffice/member/domain/MemberDto.java
src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/java/com/fiveLink/linkOffice/vacation/repository/VacationTypeRepository.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationService.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalApicontroller.java
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_edit.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_create.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_edit.html

- 등록 시 휴가 갯수 감소
- 휴가 기안 취소 시 휴가 갯수 복구
- 휴가 기안 반려 시 휴가 갯수 복구
- 신청 시 본인이 보유한 갯수보다 값이 많으면 alert

🎉 [전주영] 휴가 기안 반려시 휴가 갯수 복구

---

src/main/java/com/fiveLink/linkOffice/member/service/MemberService.java
src/main/java/com/fiveLink/linkOffice/vacationapproval/controller/VacationApprovalViewController.java
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_edit.js
src/main/resources/templates/employee/vacationapproval/vacationapproval_create.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_edit.html

- 갯수 막기 -> 둘 다 string 타입이라서 비교가 제대로 안됐음

:sparkles:[전주영] 휴가결재alert 수정

---

src/main/resources/static/css/login.css
src/main/resources/static/css/pwchange.css
src/main/resources/static/js/employee/vacationapproval/vacationapproval_create.js
src/main/resources/static/js/employee/vacationapproval/vacationapproval_edit.js

- vali_text 문구 수정
- 로그인
- 비밀번호 변경

✨[전주영] 로그인 및 비밀번호 변경 css 수정

---

src/main/java/com/fiveLink/linkOffice/mapper/VacationMapper.java
src/main/java/com/fiveLink/linkOffice/vacation/controller/VacationViewController.java
src/main/java/com/fiveLink/linkOffice/vacation/service/AddVacationSchedulerService.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationService.java
src/main/resources/mappers/vacationMapper.xml
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/css/include/nav.css
src/main/resources/static/js/employee/vacationapproval/homeVacationCount.js
src/main/resources/templates/admin/chat/chatMessage.html
src/main/resources/templates/include/nav.html

- 채팅 프로필 사진 크기 조정
- 사이드바 드롭 메뉴 구분 색 조정
- 휴가 지급 수정과 스케쥴링 확인

✨ [김채영] double형으로 휴가 개수 지급 & 메인에 휴가 지급 출력

---

src/main/resources/application.properties
src/main/resources/static/css/admin/schedule/companySchedule.css
src/main/resources/static/css/include/layout.css
src/main/resources/static/css/login.css
src/main/resources/static/js/admin/schedule/companySchedule.js
src/main/resources/static/js/employee/schedule/employeeSchedule.js
src/main/resources/static/js/employee/schedule/homeSchedule.js
src/main/resources/templates/admin/schedule/companySchedule.html
src/main/resources/templates/login.html

**로그인 css**
- login.html
- 로고 이미지 주석
- 로고 text div 추가
- login.css
- 기존 코드 주석 처리 후 코드 작성
**일정**
- 9:00 형식 출력 통일

:sparkles: [서혜원] 로그인 css 수정, 일정 시간 출력 통일

---

build.gradle
src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/resources/application.properties
src/main/resources/static/css/employee/survey/survey_create.css
src/main/resources/templates/admin/notice/notice_create.html
src/main/resources/templates/admin/notice/notice_update.html
src/main/resources/templates/home.html

✨ [김민재] 홈 공지사항 수정

---

src/main/resources/application.properties
src/main/resources/static/css/include/nav.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/static/js/include/nav.js
src/main/resources/templates/admin/chat/chatMessage.html

✨ [김채영] nav 수정

---

src/main/java/com/fiveLink/linkOffice/chat/controller/ChatRoomController.java
src/main/java/com/fiveLink/linkOffice/chat/service/ChatRoomService.java
src/main/java/com/fiveLink/linkOffice/mapper/ChatMapper.java
src/main/resources/mappers/chatMapper.xml
src/main/resources/static/js/admin/chat/chatMessage.js

:tada: [김채영] 채팅방 10개 고정 제한

---

src/main/resources/static/css/employee/attendance/myAttendance.css
src/main/resources/static/css/employee/document/bin.css
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css
src/main/resources/static/js/employee/attendance/myAttendance.js
src/main/resources/static/js/employee/document/company.js
src/main/resources/static/js/employee/document/department.js
src/main/resources/static/js/employee/document/personal.js
src/main/resources/templates/employee/document/company.html
src/main/resources/templates/employee/document/department.html
src/main/resources/templates/employee/document/personal.html

**문서함**
- 폴더 목록 없을 시 css 수정
- 체크박스 css 수정
**근태 조회**
- 달력 안에 근태 bar 전달 건 출력되지 않도록 수정

✨ [박혜선] 문서함 체크박스 css 수정

---

src/main/resources/static/css/login.css
src/main/resources/static/css/pwchange.css
src/main/resources/templates/login.html
src/main/resources/templates/pwchange.html

:sparkles:[전주영] 로그인 및 비밀번호 변경 css 수정

---

src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css

✨  [박혜선] 문서함 모달 css 수정

---

src/main/java/com/fiveLink/linkOffice/webSocket/ChatWebSocketHandler.java
src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/css/admin/organization/organizationChart.css
src/main/resources/static/css/home.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/templates/admin/chat/chatMessage.html

전반적인 채팅 기능 수정과 css 수정
메인 버튼 간격 수정

:sparkles: [김채영] 채팅 전반적인 css와 기능 오류 수정

---

src/main/resources/static/css/admin/chat/chat.css

- Swal 모달 버튼 색상 수정
- 전반적인 버튼 색상 동일하게 수정

:sparkles: [김채영] 버튼 색상 수정

---

src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingReservationController.java
src/main/java/com/fiveLink/linkOffice/meeting/repository/MeetingParticipantRepository.java
src/main/java/com/fiveLink/linkOffice/meeting/service/MeetingParticipantService.java
src/main/resources/static/css/admin/meeting/meetingReservationList.css
src/main/resources/static/css/admin/meeting/meetingroomList.css
src/main/resources/static/css/admin/organization/departmentList.css
src/main/resources/static/css/admin/organization/positionList.css
src/main/resources/static/css/admin/permission/permission.css
src/main/resources/static/css/admin/schedule/companySchedule.css
src/main/resources/static/css/admin/schedule/scheduleCategory.css
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/employee/meeting/myMeetingReservation.css
src/main/resources/static/css/employee/meeting/reservationDetail.css
src/main/resources/static/css/employee/schedule/employeeSchedule.css
src/main/resources/static/css/include/layout.css
src/main/resources/static/js/admin/permission/permissionList.js
src/main/resources/templates/admin/meeting/meetingReservationList.html
src/main/resources/templates/admin/meeting/meetingroomList.html
src/main/resources/templates/admin/schedule/companySchedule.html

✨ [서혜원] 페이지 디자인 통일

---

src/main/resources/static/css/admin/approval/approval_form.css
src/main/resources/static/css/admin/member/list.css
src/main/resources/static/css/employee/approval/approval_history_list.css
src/main/resources/static/css/employee/approval/approval_history_vacation_detail.css
src/main/resources/static/css/employee/approval/approval_progress_detail.css
src/main/resources/static/css/employee/approval/approval_progress_list.css
src/main/resources/static/css/employee/approval/approval_references_detail.css
src/main/resources/static/css/employee/approval/approval_references_list.css
src/main/resources/static/css/employee/approval/approval_reject_detail.css
src/main/resources/static/css/employee/approval/approval_reject_list.css
src/main/resources/static/css/employee/member/list.css
src/main/resources/static/css/employee/member/mypage.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_list.css
src/main/resources/static/js/admin/member/detail.js
src/main/resources/static/js/admin/member/list.js
src/main/resources/static/js/employee/member/digitalname.js
src/main/resources/templates/include/nav.html

- 상세 조회 css 수정
- js 수정 -> 선 굵기 수정
- 사원 조회 -> 사원 목록

:sparkles:[전주영] 전자결재 css 수정 및 전자서명 js 수정

---

src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/include/layout.css

**layout.css(공통 css)**
- select, input, textarea에 공통 css 적용
- swal에 focus 시 테두리 안 생기게 하는 코드 추가
**문서함**
- 문서함 검색 select css 수정

✨  [박혜선] 공통 css 수정

---

src/main/resources/static/css/admin/inventory/inventory_create.css
src/main/resources/static/css/admin/inventory/inventory_list.css
src/main/resources/static/css/admin/notice/notice_create.css
src/main/resources/static/css/admin/notice/notice_detail.css
src/main/resources/static/css/admin/notice/notice_list.css
src/main/resources/static/css/admin/notice/notice_update.css
src/main/resources/static/css/employee/survey/survey_create.css
src/main/resources/static/css/employee/survey/survey_end_list.css
src/main/resources/static/css/employee/survey/survey_ing_list.css
src/main/resources/static/css/employee/survey/survey_my_list.css
src/main/resources/static/css/employee/survey/survey_question_detail.css
src/main/resources/static/css/employee/survey/survey_question_myResult.css
src/main/resources/static/css/employee/survey/survey_question_result.css
src/main/resources/templates/admin/inventory/inventory_create.html

✨ [김민재] css 수정

---

src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/css/admin/organization/organizationChart.css
src/main/resources/templates/admin/chat/chatMessage.html

:sparkles: [김채영] 채팅 조직도 버튼 오른쪽 정렬

---

src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/css/admin/vacation/addVacation.css
src/main/resources/static/js/admin/chat/chatMessage.js
src/main/resources/static/js/admin/vacation/vacationStandard.js

✨ [김채영] 채팅 css 수정

---

src/main/resources/static/css/employee/document/bin.css
src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css

✨  [박혜선] 문서함 체크박스 css 수정

---

src/main/resources/static/js/employee/attendance/myAttendance.js

**근태**
- 공휴일&주말 날짜 색상 출력 오류 수정

✨  [박혜선] 근태 조회 공휴일&주말 날짜 색상 출력 오류 수정

---

src/main/resources/application.properties
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/home.css

:sparkles: [서혜원] 메인 페이지 css 수정

---

src/main/resources/static/js/employee/schedule/homeSchedule.js

:sparkles: [서혜원] 메인 일정 휴가 모달 추가

---

src/main/java/com/fiveLink/linkOffice/inventory/controller/InventoryApiController.java
src/main/java/com/fiveLink/linkOffice/meeting/controller/MeetingController.java
src/main/java/com/fiveLink/linkOffice/notice/controller/NoticeApiController.java
src/main/resources/application.properties
src/main/resources/static/js/admin/vacation/addVacation.js
src/main/resources/templates/admin/inventory/inventory_list.html
src/main/resources/templates/admin/vacation/addVacation.html

- swal 수정
- swal 수정
- 
- swal 수정
- 
- swal 수정
- 휴가 값 지정 type text-> number 변경

:sparkles:[전주영] 관리자측 swal 수정

---

src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/css/employee/attendance/myAttendance.css
src/main/resources/static/css/employee/member/myedit.css
src/main/resources/static/css/employee/schedule/employeeSchedule.css
src/main/resources/templates/employee/vacationapproval/vacationapproval_list.html

사용자측 css 수정

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/employee/attendance/myAttendance.css

✨ [김채영] 근태 css 수정

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/admin/approval/approval_detail.css
src/main/resources/static/css/employee/member/myedit.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/static/css/login.css
src/main/resources/templates/admin/approval/approval_detail.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html

- 전자결재 양식 관리 상세 조회 
- 버튼 위치 수정
- css 수정

✨[전주영] 전반적인 css 수정

---

src/main/resources/static/css/employee/document/company.css
src/main/resources/static/css/employee/document/department.css
src/main/resources/static/css/employee/document/personal.css

**문서함**
- height 코드 없앰
- 테이블 크기 줄임
- 테이블 위에 버튼 간격 넓힘 
- 파일명이 td에 설정된 width를 넘어갈 시 hidden 처리 하고 '...'으로 표시

✨  [박혜선] 문서함 css 수정

---

src/main/java/com/fiveLink/linkOffice/HomeController.java
src/main/resources/static/css/admin/schedule/companySchedule.css
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/employee/meeting/reservationDetail.css
src/main/resources/static/css/employee/schedule/employeeSchedule.css
src/main/resources/static/css/include/layout.css
src/main/resources/static/js/employee/schedule/homeSchedule.js

1. 메인 페이지 일정
- 사원명 null 오류 수정
2. 회의실, 일정 참여자 span 수정
3. 일정 plus_detial_option 수정
4. layout.css button curosr 디자인 추가
input[type='button']{ 
cursor: pointer;
}

:sparkles: [서혜원] 일정 사원명 오류 수정

---

src/main/resources/static/css/admin/chat/chat.css
src/main/resources/static/css/admin/vacation/vacationStandard.css

:sparkles: [김채영] 채팅 css와 휴가 css 수정

---

src/main/resources/static/css/admin/member/detail.css
src/main/resources/static/css/employee/approval/approval_history_vacation_detail.css
src/main/resources/static/css/employee/approval/approval_progress_detail.css
src/main/resources/static/css/employee/approval/approval_references_detail.css
src/main/resources/static/css/employee/approval/approval_reject_detail.css
src/main/resources/static/css/employee/member/detail.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css
src/main/resources/templates/admin/member/detail.html
src/main/resources/templates/employee/approval/approval_progress_detail.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_detail.html

:sparkles:[전주영] 결재 목록 css 수정

---

src/main/resources/application.properties
src/main/resources/static/css/admin/vacation/vacationStandard.css
src/main/resources/static/css/employee/meeting/meetingReservation.css
src/main/resources/static/css/employee/meeting/reservationDetail.css
src/main/resources/static/css/employee/schedule/employeeSchedule.css
src/main/resources/static/css/home.css

✨ [김채영] 홈 일정 모달 수정

---

src/main/resources/static/js/employee/member/digitalname.js

:sparkles:[전주영] 전자서명 등록 굵기 수정

---

src/main/resources/static/js/employee/document/company.js
src/main/resources/templates/include/nav.html

- nav.html 사내 문서함 -> 전사 문서함으로 수정
- 사내 문서함 js에 경로 사내 문서함 -> 전사 문서함으로 수정

✨  [박혜선] 사내 문서함->전사 문서함으로 호칭 수정

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/admin/chat/chat.css

:sparkles: [서혜원] 채팅 버튼 색상 복구

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/login.css
src/main/resources/static/css/pwchange.css
src/main/resources/static/js/login.js
src/main/resources/static/js/pwchange.js
src/main/resources/templates/login.html
src/main/resources/templates/pwchange.html

- capslock 이 눌려있는 지 확인하여 "켜져있습니다" 문구 출력

✨[전주영] 로그인 및 비밀번호 변경 시 caps lock 이벤트 확인

---

src/main/resources/templates/employee/survey/survey_question_update.html

:sparkles: [김채영] 설문 수정 오류 수정

---

build.gradle
src/main/resources/application.properties
src/main/resources/static/css/employee/meeting/reservationDetail.css

:sparkles: [서혜원] 회의실 상세 css 수정

---

src/main/java/com/fiveLink/linkOffice/vacation/service/VacationSchedulerService.java
src/main/resources/static/css/employee/approval/approval_history_vacation_detail.css
src/main/resources/static/css/employee/approval/approval_progress_detail.css
src/main/resources/static/css/employee/approval/approval_references_detail.css
src/main/resources/static/css/employee/approval/approval_reject_detail.css
src/main/resources/static/css/employee/vacationapproval/vacationapproval_detail.css

:sparkles:[전주영] 결재 css 수정

---

src/main/resources/templates/employee/survey/survey_question_myResult.html

:sparkles: [서혜원] 설문 삭제 swal 삭제 -> 확인

---

src/main/java/com/fiveLink/linkOffice/survey/service/SurveySchedulerService.java
src/main/java/com/fiveLink/linkOffice/vacation/service/VacationSchedulerService.java
src/main/resources/application.properties
src/main/resources/static/css/employee/approval/approval_history_list.css
src/main/resources/static/css/employee/survey/survey_create.css
src/main/resources/static/css/include/header.css
src/main/resources/templates/admin/notice/notice_detail.html
src/main/resources/templates/employee/vacationapproval/vacationapproval_list.html

:sparkles: [김채영] css 수정

---

src/main/java/com/fiveLink/linkOffice/approval/controller/ApprovalViewController.java
src/main/java/com/fiveLink/linkOffice/member/repository/PermissionCodeRepository.java
src/main/java/com/fiveLink/linkOffice/security/config/WebSecurityConfig.java

- 쿼리 수정 ( 상태가 0인 것만 조회 )
- 역할에 따른 경로 설정

:sparkles:[전주영] 권한 역할 쿼리 수정 및 security 경로 설정
